### ISSUE TITLE
how detect colision info from 2 meshes ?

### ISSUE THREAD

**Issue by EpicSpaces** [irlanrobson/bounce#1]
I'm in love with this lib, so what is the code to how detect collision informations from 2 meshes ?

**Comment by irlanrobson** [comment]
Thanks.

Collision between two triangle meshes is not supported. Only collision between spheres, capsules, convex hulls and static triangle meshes is supported.

**Comment by EpicSpaces** [comment]
I know, what I was trying to say is what code should I write to report me the collision info

**Comment by irlanrobson** [comment]
You can get a contact manifold by calling `b3Contact::GetWorldManifold` on a mesh contact.

**Comment by irlanrobson** [comment]
For collision events see `b3ContactListener`. This should get you the begin, pre-solve, and end contact events. All you need to do is to attach a listener to a world using the function `b3World::SetContactListener`.

**Comment by irlanrobson** [comment]
You can loop over the contact manifolds inside a contact using:
```

for (u32 index = 0; index < contact->GetManifoldCount(); ++index)
{
        b3WorldManifold manifold;
        contact->GetWorldManifold(&manifold, index);
        
        // Loop over the contact points inside the manifold.
}

```

**Comment by EpicSpaces** [comment]
I may ask more deeper about aabb tree and all that stuff later ... but is any multi-threading clue, looks a little bit slower, shouldn't be implemented in the step function. (just please don't tell me you too again that's just an experiment and you can't compete with physix or bullet, because you will offense me and I will take that personally)

**Comment by irlanrobson** [comment]
Sorry, I don't plan to do multithreading in this library soon. Any optimization is done mostly in the algorithmitic level. This library doesn't contain experiments. You can use it for real interactive applications. This engine can be seen as an alternative to existent libraries like Bullet.

**Comment by EpicSpaces** [comment]
:) I love this lib more, because I've already builded a complete(almost) engine renderer, but needed some physics, if one to implement multithreading to this library from where should I start ? I really want you to plan, please plan plan, or give me some more clues about how multithreading would work, architecture etc ... I hate those big and heavy frameworks like physx where the code is unreadable and complicated,(why they coded it like that, just to don't understand anything)

**Comment by irlanrobson** [comment]
I think I would start trying to multithreading the islands using a thread pool. Islands can be solved separately so this can be easy to implement. See b3Island.h/cpp.

In addition to that, I think Bullet contains some examples on multithreading but the code is a little cumbersome to read. 

Also, there is a project called Box2D multithreaded that may help since Bounce is hugely based around Box2D:

https://github.com/jhoffman0x/Box2D-MT

**Comment by EpicSpaces** [comment]
thanks :), I'm going to return to threading sooner, for now I have to get more flexible with the lib.
as you said, maybe the only way to get the mesh/rigidbody shape colliding (e.g like a trigger) is with contact manifolds, or we can get it directly ?

**Comment by irlanrobson** [comment]
I think what you are asking for is a contact listener. See `b3ContactListener`. See `b3World`. There is a callback there that can be set.

**Comment by EpicSpaces** [comment]
can you build a collider from mesh ? it would be exciting

**Comment by irlanrobson** [comment]
Yes, any triangle mesh can collide with spheres, capsules, and convex hulls. See the mesh contact test in the Testbed for an example.

**Comment by EpicSpaces** [comment]
I love you man, you saved my life with this lib, I can
