### ISSUE TITLE
Question: Does b3SphereShape::ComputeAABB need to rotate m_center?

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#11]
I'm using Bounce on a SEGA Dreamcast game, and as you can imagine that's a fairly resource constrained system! 

Everything is working fine, but I'm trying to squeeze out some last bits of performance.

Interestingly, 3% of my frame-time is going into `b3SphereShape::ComputeAABB` - specifically it's the subsequent calls to b3Mul, and b3Cross. 

I was wondering if that rotation is necessary there, or is it enough to just add `m_center` to `xf.translation`?

**Comment by irlanrobson** [comment]
Yeah, it needs to account for the body rotation. You can try converting the rotation to a matrix and apply it to the center before translating it.
