### ISSUE TITLE
Possible problem with b3MeshShape::RayCast?

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#15]
I've successfully implemented support for Box and Sphere collider shapes in my game engine using Bounce, and I am currently implementing support for mesh shapes. I've followed the same pattern as before but instead of `b3BoxHull` + `b3HullShape` I'm using `b3Mesh` and `b3MeshShape`. So I generate a b3Mesh once, call `BuildTree()` after specifying vertex and triangle data, then create a `b3MeshShape` and pass it to `CreateShape`.

My problem is that when I try to write a test case in my game engine (using `world->RayCast`) the RayCast doesn't return a hit and I can't figure out why.

My test involves creation a 1.0 diameter cube mesh shape around 0, 0, 0. Then performing a ray cast from (0, 2, 0) to (0, 0, 0) (e.g. downward) but the ray cast never returns a hit. I've stepped through the code, and the cast never enters this if statement: https://github.com/irlanrobson/bounce/blob/8defab994568f381e1d6efc036d1f63c42942aa4/src/bounce/dynamics/shapes/mesh_shape.cpp#L111

I noticed that the variable `offset` in that function is never used, and I wondered if that's a mistake?

**Comment by Kazade** [comment]
OK a little more info. When I step into where I believe there should be an intersection and I get to the if statement with the barycentric coordinates, the variables are as follows:

```
q == (0, 0.5, 0)
v1 == (0.5, 0.5, -0.5)
v2 == (-0.5, 0.5, 0.5)
v3 == (0.5, 0.5, 0.5)
w == (0.5, 0.5, 0.0, 1.0)
```

It looks to me like the raycast hits the very edge of the triangle (which passes through (0, 0.5, 0)), potentially an edge case?

**Comment by irlanrobson** [comment]
That if statement checks if the contact point of the ray segment with the face plane is lying on the triangle.

**Comment by irlanrobson** [comment]
You haven't pulled the last version of the library. The version you're using is not updated since Barycentric function was renamed to BarycentricCoordinates to distinguish it from the Barycentric function in gjk.cpp.

**Comment by irlanrobson** [comment]
Anyhow... The offset variable stores the offset of the triangle face plane in mesh coordinates. I would have to investigate this to see if there is a problem.

**Comment by Kazade** [comment]
Yeah you're right. I've just updated, but I still see the same issue. If the ray cast hits the boundary of two triangles which are side-by-side then it doesn't report a hit. If I shift the ray slightly then it reports a hit fine.

**Comment by irlanrobson** [comment]
There is one bug and one issue. 

(1) The world transform stored in b3MeshRayCastCallback is not being initialized. 
(2) The world transform passed to the function that performs a ray cast against a child triangle of the mesh is not converting the ray or segment from world coordinates to mesh coordinates. The conversion is necessary if the user requires performing a ray cast against a specified triangle. 

These are being fixed now. Thank you for the file.

**Comment by irlanrobson** [comment]
Thinking about it, unfrequently an user performs ray casts against child shapes.

**Comment by Kazade** [comment]
I might not be understanding this correctly (my mathematics skills are terrible) but wouldn't a raycast hit on the edge of a triangle return a barycentric value of 0? Should the if statement be testing for `>= 0` rather than `> 0`? Presumably coordinates outside of the triangle would result in negative values?

**Comment by irlanrobson** [comment]
Theoretically testing against zero is correct, but practically this has little consequence due to floating point precision.

**Comment by irlanrobson** [comment]
Some changes have been made. Does that  solve your problems?

**Comment by Kazade** [comment]
No, unfortunately not :(

Changing the if statement to this fixes it: `if (w[0] >= 0.0f && w[1] >= 0.0f && w[2] >= 0.0f)` but then I don't know what side effect that will have elsewhere.

**Comment by irlanrobson** [comment]
Now answering your last two questions. 

Yes, a vertex lying exactly on an edge of a triangle in cartesian coordinates maps to a zero vector in barycentric coordinates with respect to the triangle. 

If a vertex is exactly on a shared edge then a tolerance value is necessary. Sorry, I should have catched this while deriving those formulas in my drafts. Thanks.

**Comment by irlanrobson** [comment]
Right. A global radius value will be used for extending the side planes of the three triangle edges. Ideally this value should be used only for extending the side planes of shared edges.

**Comment by irlanrobson** [comment]
Now an absolute tolerance value has been defined for use in the point-on-triangle test. So certainly the test can fail if the triangle edges vary greatly in length. Computing the three edge side planes, adding a global radius to them, and testing if the intersection is inside is an alternative solution and adds more controlability to the tolerance value. However, it evaluates three square roots to normalize the side planes. So I kept the simpler solution.

Kazade, does that solves your problems?

**Comment by Kazade** [comment]
I believe it does, I can't check right now but I'll do so tomorrow. Thanks!

**Comment by Kazade** [comment]
Yep, I can confirm this fixes my issue. Thanks!
