### ISSUE TITLE
Collision between b3MeshShape and b3HullShape causes an assertion error

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#16]
Sorry, I bet you're getting sick of me! 😄 

I'm hitting an assertion on this line: https://github.com/irlanrobson/bounce/blob/master/src/bounce/dynamics/contacts/collide/collide.cpp#L181

This happens when a box shape (b3HullShape) collides with a mesh (b3MeshShape)

Just want to say I really appreciate your work on this project and the support you've been giving me! Thank you!

**Comment by irlanrobson** [comment]
Not at all. That's a great contribuition.

**Comment by irlanrobson** [comment]
b3CollideShapeAndShape must not be called if one of shapes is a mesh. I'll put an assert on this condition.

**Comment by irlanrobson** [comment]
Are you calling this function explicitly?

**Comment by Kazade** [comment]
No I'm just creating the two bodies and their shapes and then one is falling into another. But actually, maybe this only happens on mesh Vs mesh! I'll try again later when i get home (travelling).

**Comment by Kazade** [comment]
Actually yes I'm pretty sure my initial report is wrong. This is happening when two meshes collide rather than a box and mesh. Sorry!

**Comment by irlanrobson** [comment]
Collision between meshes is not implemented. That is a difficult problem to solve efficiently. Usually artists only use meshes to represent static objects in the game. For example, a game level.

**Comment by Kazade** [comment]
Ok that's fine, that makes sense. Feel free to close this issue then :)
