### ISSUE TITLE
EndContact isn't called when contacts stop overlapping

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#18]
See here: https://github.com/irlanrobson/bounce/blob/5cc72c5940a50380a04b04bdb9c0f5b9462510aa/src/bounce/dynamics/contact_manager.cpp#L223

The contact is destroyed before `c->Update()` is called, so if two shapes stop overlapping any b3ContactListener watching for it isn't notified.

**Comment by Kazade** [comment]
Sorry, ignore me. Something else must be wrong

**Comment by irlanrobson** [comment]
This report is wrong. The contact listener will be notified when the following line is reached.

https://github.com/irlanrobson/bounce/blob/5cc72c5940a50380a04b04bdb9c0f5b9462510aa/src/bounce/dynamics/contact_manager.cpp#L281
