### ISSUE TITLE
BeginContact not fired a second time

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#19]
This is probably something I'm doing, or I'm misunderstanding so bear with me :)

I have a test which does the following:

1. Creates a static body (A) at 0,0,0 with a box hull shape (width 1.0)
2. Creates a dynamic body (B) at 0,0,0 with a box hull shape (width 1.0)
3. Runs one `Step()`. Checks that BeginContact is fired. <<< WORKS
4. Moves B to 0,10,0
5. Runs one `Step()`. Checks that EndContact is fired <<< WORKS
6.  Moves B to 0,0,0
7. Runs one `Step()`. Checks that BeginContact is fired.  <<< THIS FAILS :(

Firstly, I know you normally shouldn't move stuff around with `SetTransform` but I'm just doing this as a test to make sure my contact listener is working :)

I've tried stepping through the code, and I can see that when the B is added, the contacts are created here: https://github.com/irlanrobson/bounce/blob/master/src/bounce/dynamics/world.cpp#L105

And I can see when I move B away, the contacts are removed here:  https://github.com/irlanrobson/bounce/blob/master/src/bounce/dynamics/contact_manager.cpp#L222

But I can't see where they are created again if the object starts colliding a second time. Am I doing something wrong?

**Comment by irlanrobson** [comment]
Are you modifying the position inside the simulation callbacks?

Store the body pointer inside the class that implements the contact listener and modify its position after stepping the world. See if that solves your problem. Also, you cannot create or destroy bodies inside the callbacks.

**Comment by irlanrobson** [comment]
This problem is not present in my test. Even if the body position is modified inside the callbacks. If I put a breakpoint in BeginContact and EndContact and step through the debugger then it just keeps ping-ponging from one to the other infinitely. 

Assume m_bA and m_bB is the bodies in your example. That's how I'm writing this test case:

```

	void BeginContact(b3Contact* contact)
	{
		b3Shape* sA = contact->GetShapeA();
		b3Shape* sB = contact->GetShapeB();

		b3Body* bA = sA->GetBody();
		b3Body* bB = sB->GetBody();

		bool hasBodyA = bA == m_bA || bB == m_bA;
		bool hasBodyB = bA == m_bB || bB == m_bB;

		if (hasBodyA && hasBodyB)
		{
			b3Quat q = m_bB->GetOrientation();
			b3Vec3 axis;
			float32 angle;
			q.GetAxisAngle(&axis, &angle);

			b3Vec3 p = m_bB->GetPosition();
			p.Set(0.0f, 10.0f, 0.0f);
			
			m_bB->SetTransform(p, axis, angle);
		}
	}
	
	void EndContact(b3Contact* contact)
	{
		b3Shape* sA = contact->GetShapeA();
		b3Shape* sB = contact->GetShapeB();

		b3Body* bA = sA->GetBody();
		b3Body* bB = sB->GetBody();

		bool hasBodyA = bA == m_bA || bB == m_bA;
		bool hasBodyB = bA == m_bB || bB == m_bB;

		if (hasBodyA && hasBodyB)
		{
			b3Quat q = m_bB->GetOrientation();
			b3Vec3 axis;
			float32 angle;
			q.GetAxisAngle(&axis, &angle);

			b3Vec3 p = m_bB->GetPosition();
			p.Set(0.0f, 0.0f, 0.0f);

			m_bB->SetTransform(p, axis, angle);
		}
	}
	
```

**Comment by Kazade** [comment]
Hmm... thanks, I'll keep digging around and see if I can work out what I'm doing differently.

**Comment by Kazade** [comment]
OK, for what it's worth, this was what fixed my problem (note this is my game engine API which calls through to Bounce:

```        
        body2->move_to(Vec3(0, 0, 0));
        body2->set_linear_velocity(Vec3(0, 0, 0)); // Just in case
        physics->fixed_update(1.0f / 60.0f); // < This didn't work on its own
        physics->fixed_update(1.0f / 60.0f); // < This did
        assert_true(enter_called); //< This correctly detects the contact started
```

I'm guessing it's something to do with the order that contacts are created + notified within the `Step()` (e.g. the contact is created in the first step, but too late for the `BeginContact` signal)

**Comment by irlanrobson** [comment]
BeginContact is called once two shapes start overlapping with each other.
EndContact is called once two shapes stop overlapping with each other.
PreSolve is called everytime the shapes are colliding. 

A contact exists for every pair of overlapping shape AABBs, but the callbacks above are triggered only if the shapes overlap.

**Comment by irlanrobson** [comment]
So, a contact may still be created if the shape AABBs are overlapping, but the callbacks are only triggered if the shapes are overlapping. If you want to check if the **shapes** are colliding at any moment use b3Contact::IsOverlapping().

**Comment by irlanrobson** [comment]
Have you tried the example I posted above? If you put a breakpoint on both callbacks they should keep being called infinitely. That's the expected behaviour of the test described in the first comment.

**Comment by irlanrobson** [comment]
The test described in your last comment was reproduced and there were no problems. BeginContact is called during the first Step call. Inside the second Step call the callback is not triggered as the shapes are still overlapping, but PreSolve is.

**Comment by Kazade** [comment]
Hmm, ok I'll take another look tomorrow. Here's the full test just in case you spot anything obvious:

https://github.com/Kazade/simulant-engine/blob/cleanup-physics-api/tests/test_physics.h#L110

**Comment by irlanrobson** [comment]
Thanks for the code implementing this unit test. I am reproducing it now.

**Comment by irlanrobson** [comment]
After the body is positioned at coordinate (0, 10, 0) and Step is called, the contact will be destroyed since contacts are updated inconditionally.

Now if you position it at (0, 10, 0) and call Step, current contacts will be updated before creating new contacts since shapes weren't created. But there are no contacts to be updated. Hence, the contact listener won't be notified. However, new contacts will be created at the end of this step, and contacts will be updated at the beginning of the next step. 

You can tell the world to find new contacts at the beginning of the next step by turning on the flag e_shapeAddedFlag after changing the transform of a body like so:

inline void b3Body::SetTransform(const b3Vec3& position, const b3Vec3& axis, float32 angle) 
{
	b3Quat q = b3Quat(axis, angle);
	
	m_xf.position = position;
	m_xf.rotation = b3ConvertQuatToMat(q);

	m_sweep.worldCenter = b3Mul(m_xf, m_sweep.localCenter);
	m_sweep.orientation = q;

	m_sweep.worldCenter0 = m_sweep.worldCenter;
	m_sweep.orientation0 = m_sweep.orientation;

	SynchronizeShapes();

        // Here:
	m_world->m_flags |= b3World::e_shapeAddedFlag;
}

**Comment by irlanrobson** [comment]
An alternative is to unconditionally find new contacts at the beginning of each frame before updating the contacts like so:


```
void b3World::Step(float32 dt, u32 velocityIterations, u32 positionIterations)
{
	B3_PROFILE("Step");

	m_contactMan.FindNewContacts();
        m_contactMan.UpdateContacts();

        ...
}
```

However this change certainly decrease performance.

**Comment by Kazade** [comment]
Excellent, thanks for that information - that explains what I'm seeing so I'll just leave the test as it is with a comment. Thanks again for all your help!
