### ISSUE TITLE
Quick fixes for Linux builds.

### ISSUE THREAD

**Issue by JodiTheTigger** [irlanrobson/bounce#2]
* Fix issue #1 
 * change
```cpp
template <class T>
inline T b3Abs(T x) 
{
	return abs(x);
}
```
to
```cpp
template <class T>
inline T b3Abs(T x) 
{
    return std::abs(x);
}
```
 * Add a unix based `time.cpp` implementation
 * add `#include <stdio.h>` to `debug_draw.cpp` and `main.cpp`
 * Either remove `sprintf_s` or roll you're own version, or require C11 support (which has sprintf_s)

**Comment by RandyGaul** [comment]
For time I have some reference code here you can take a look at Irlan, maybe save you a little time (pun intended haha) https://github.com/RandyGaul/tinyheaders/blob/master/tinytime.h

**Comment by irlanrobson** [comment]
Thanks JodiTheTigger, the changes have been made but not commited yet :).  

Thanks for this Randy. This engine will hopefully run on Linux till the christimas.
