### ISSUE TITLE
Question: What's the best way to constrain rotations?

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#21]
I have a hover ship (box collider) which is controllable by the player which works fine as long as I don't crash into anything. I'd like to prevent rotation on the X + Z axis, and only allow rotation on the Y.

Unity has this using their RigidBody constraints system (https://docs.unity3d.com/ScriptReference/Rigidbody-constraints.html) I'd like to do something similar in Bounce, what's the best way to achieve that without breaking things?

Thanks!

**Comment by irlanrobson** [comment]
Set the flag `fixedRotationY` in `b3BodyDef`  to `true`.

**Comment by Kazade** [comment]
Aha! Thanks :)
