### ISSUE TITLE
Dreamcast implementation of b3Time

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#22]
I'm not sure you need/want this in the codebase as it's a niche thing, but I just thought I'd let you know that this exists: https://github.com/Kazade/bounce/commit/83e44dc5eb09f009803378ecb504c8c3f7143c64

It compiles but I haven't tested it yet.

**Comment by irlanrobson** [comment]
Thank you for letting me know. This small contribution isn't good as the engine it's being developed on Windows. If you ever develop a well tested port please let me know and I'll figure out a way of linking to it. Note the engine should run just fine on a 360.
