### ISSUE TITLE
Rope 

### ISSUE THREAD

**Issue by irlanrobson** [irlanrobson/bounce#23]
Rope simulation might blow up eventually because of the velocity squared forces that gets propagated up and down the chain, even when applying damping forces on joints or bodies. Therefore it's recommended to take small substeps when simulating ropes and increase the coefficient of damping.

One possible solution is to try another numerical integration methods. For example, adaptive quadrature (with a symplectic integrator). However, this is not free. A lot of substeps might be necessary to reach a reasonable accuracy. For those who are interested I recommend running the following example.

```
// Example program
// Adaptive integration (without recursion)
#include <string>
#include <stdlib.h>

int main()
{
	// Stiff system
	float k = 50000.0f;
	
	// State
	float x = 1.0f, v = 0.0f;
        
        // Step size
	float h = 0.01f;
	
	float min_h = 1.0f / 2000.0f;
	int max_n = 20;

	// Decrease these values if more accuracy is required.
	float abs_tol = 10.0f * FLT_EPSILON;
	float rel_tol = 0.01f;	

	for (int i = 0; i < 120; ++i)
	{
		float v1 = v - k * h;
		float x1 = x + v1 * h;

		float v0 = v1;
		float x0 = x1;

		int n = 2;

                // Substep size
		float h_j = h;

		while (n < max_n)
		{
			h_j /= float(n);
			
			// Ensure a computer representable substep size.
			if (h_j < min_h)
			{
				break;
			}

			float v2 = v;
			float x2 = x;
			for (int j = 0; j < n; ++j)
			{
				v2 = v2 - k * h_j;
				x2 = x2 + v2 * h_j;
			}
	
			// Assume x2 is more accurate than x1 because 
			// it contains summed integrals over smaller substeps.
			
			float abs_d = abs(x1 - x2);
			float max_abs = fmax(abs(x1), abs(x2));
			
			// Will the tolerance decrease after multiplication?
			if (max_abs <= 1.0f)
			{
				// Use absolute tolerance comparison.
				if (abs_d <= abs_tol)
				{
					// v2 wins
					v1 = v2;
					x1 = x2;
					break;
				}
			}
			else
			{
				// Use relative tolerance comparison.
				// Skip division by zero.
				if (abs_d <= rel_tol * max_abs)
				{
					// v2 wins
					v1 = v2;
					x1 = x2;
					break;
				}
			}

			// Swap solutions.
			v1 = v2;
			x1 = x2;

			++n;
		}

		v = v1;
		x = x1;

		printf("\n\n x0 = %.9g, n = 1, h = %.9g", x0, h);
		printf("\n x = %.9g, n = %d, h = %.9g", x, n, h_j);
	}

	printf("\n");
	system("pause");
	return 0;
}
```

**Comment by rosemick3d** [comment]
So many thanks to you for providing this simple and beautiful implementation and the whole library. I had been struggling with Featherstone's solvers for a long time. Learning from your code is much simpler to understand. 

Have you extended the solver to deal with tree-like structures? What about closed loops? If yes, how to you represent the links in the tree? Using an array like Bullet physics library does?

**Comment by irlanrobson** [comment]
Hi there. You're welcome, I'm glad I could help you with your studies :). 

Yeah, the derivation of Featherstone's algorithm is somewhat difficult to digest at first. Fortunatelly the results are really simple to implement. It took me 1 month to understand and come up with a reasonable implementation. It'll take probably another month to solve some instability problems :). 

Yeah, I have implemented the algorithm for body trees with different joint types, but haven't for body graphs. 

No, I haven't used Bullet as a reference when implementing the API. Personally I have a b3BodyTree class which is a tree structure of b3TreeBody objects. Then I have a base b3TreeJoint class which I inherit different joint types from. Bodies get stored in the tree as an linked list to allow O(1) insertion and removal of bodies.

**Comment by rosemick3d** [comment]
Excellent, thanks for sharing your implementation details, now I understand. Please keep up the good work whenever possible!

**Comment by irlanrobson** [comment]
I have forgotten to add that each tree body has a list of children bodies and an inboard joint. It behaves just like any body in a world. The user can add shapes to it so that they contribute to the local center of mass of the body. From there it should be pretty simple to write ABA and optimizable.
