### ISSUE TITLE
Rope Constraints

### ISSUE THREAD

**Issue by rosemick3d** [irlanrobson/bounce#25]
Quick questions. Isn't it much simpler define a rope as rigid bodies and spherical joints? 
Could could you reuse the solver implemented in b3SphereJointr?

**Comment by irlanrobson** [comment]
Do you mean copying b3Body and b3Joint and simplify? Well, that is equivalent to building a rope using the bodies (b3Body) and spherical joints (b3SphereJoint) that a world supplies. For example, run the MultiplePendulum test in the Testbed, which is kind of a stress test showing how the rope behaves when using the iterative solver implemented here and large mass ratios. 

So yes, it's simpler and you can use whatever solver you like. 

Now a couple of important notes in the case you're trying to implement such a system. 

In theses cases we're operating in maximal coordinates (or Lagrange multiplier) methods and there are constraints to be satisfied. As you probably know b3Rope operates in reduced coordinates (e.g. Featherstone) and there are no constraints to be satisfied. A dynamic base body has 6 motion degrees of freedom (dof) and a link only 3. I store a quaternion (and not 3 Euler angles) to represent the 3 rotational dof that each link has. The angular velocity is stored in body Cartesian coordinates. The time derivative of a local rotation quaternion is different from the time derivative of a global rotation.

If you have no option but work with maximal coordinates you can implement a direct solver like Baraff's:

http://www.cs.cmu.edu/~baraff/papers/sig96.pdf

I have implemented this algorithm. It works fine. You can use b3SphereJoint as a reference when implementing it. Post a question here if you have troubles with this.

Getting good physics simulation in games is not about implementing direct solvers. It's all about tweaking the system correctly to cooperate with iterative solvers.

**Comment by irlanrobson** [comment]
Does that answer the questions?

**Comment by rosemick3d** [comment]
Yes, it does answer the questions. Thanks to you very much !

**Comment by rosemick3d** [comment]
So basically you do not recommend direct solvers for games...

**Comment by irlanrobson** [comment]
That hasn't been said. You should read my post again.

Featherstone is a direct solver. It helps a lot in ragdoll physics. It's a good choice for games because its algorithmic performance is linear. However, you still can get good simulation quality with an iterative solver. You need to balance the ragdoll inertia correctly and use a small time step to reduce errors due to numerical integration. For example, ensure the torso supports the arms and legs.

**Comment by rosemick3d** [comment]
Thanks. It makes sense.
