### ISSUE TITLE
Networked Physics

### ISSUE THREAD

**Issue by kklouzal** [irlanrobson/bounce#28]
Would this library be suitable in a networked environment where multiple clients share an approximation of a singular host simulation?

**Comment by irlanrobson** [comment]
According to the GDC Physics Tutorials, a few Valve and Blizzard's game titles evidently are using similar simulation techiques that are run in the host and shared across clients. Therefore, despite of my lack of understanding in Networked Physics, it's my accurate guess it would be suitable for Networked Game Physics.

**Comment by kklouzal** [comment]
Awesome that's very good to hear! Thank you for your time and dedication to this project!
