### ISSUE TITLE
Different collision types fall at different speeds.

### ISSUE THREAD

**Issue by kaervin** [irlanrobson/bounce#29]
Hello,
I have noticed that in the testbed, objects of different collision types, such as cube or sphere fall at varying speeds.
This is especially noticeable in the 'quadric shapes' test, but also in 'shape stacks'.
If this would be fixed, this seems like a great library to use for gamephysics.

**Comment by kaervin** [comment]
Further tests make it seem that even just making spheres with different sizes causes them to fall at different speeds.

**Comment by irlanrobson** [comment]
These are not errors. It happens because objects can have different mass properties. The mass properties of a rigid body depends on the shape and density.

**Comment by kaervin** [comment]
The speed of falling Objects (affected by gravity) is independent of its weight.
https://en.wikipedia.org/wiki/Free_fall#Uniform_gravitational_field_without_air_resistance

**Comment by kaervin** [comment]
Not multiplying the gravity by the inverse Mass in b3Island::Solve seems to be the solution.
```
// Integrate forces
b3Vec3 force = b->m_force + b->m_gravityScale * gravity;
v += h * b->m_invMass * force;
```
becomes
```
v += h * (b->m_invMass * b->m_force +  b->m_gravityScale * gravity);
```

**Comment by RandyGaul** [comment]
a = f / m

If you consider gravity an acceleration it should be summed. If you consider it a force, then gravity should be multiplied by inverse mass.

**Comment by kaervin** [comment]
Since the force gravity exerts on an Object is proportional to its mass:
m: mass of our Object
M: mass of Earth
r: radius (which we can mostly ignor)
F = m * (G*M / r^2) 

and acceleration is inversely proportional to it's mass:
a = F / m

the effect the mass of the object has on the acceleration cancels out:
a = (m*(G*M / r^2)) / m
a = (G*M / r^2) which is g

which means under no other forces:
v += h * g

plus other forces (Fo) acting on it:
v += h * g +  h * (Fo / m) 

which results in
```
v += h * (b->m_invMass * b->m_force +  b->m_gravityScale * gravity);
```

**Comment by irlanrobson** [comment]
Now Bounce considers gravity as an acceleration vector (m/s^2) rather than a force vector. Indeed that was a bug.
