### ISSUE TITLE
Incorrect assert condition in b3DynamicTree

### ISSUE THREAD

**Issue by haik0925** [irlanrobson/bounce#30]
I wrote code that does destroy bodies and recreate them.
And just after the code executed, the assertion in b3DynamicTree::GetAABB stopped the program during the step function call.
This is the assert statement: B3_ASSERT(proxyId < m_nodeCount);
The dynamic tree manages node by using a linear array and free list, so I suppose It should check proxyId(which is index of a node I think) with m_nodeCapacity not m_nodeCount...?

(Sorry for my poor English if you didn't understand what I wrote 😢)

**Comment by irlanrobson** [comment]
proxyId is the index of an active node in the tree. 

I didn't understand your question. The proxyId passed to GetAABB will always be referring to an active proxy. 

What function is calling GetAABB?

**Comment by haik0925** [comment]
b3DynamicTree::GetAABB(int proxyId) Line 134
b3BroadPhase::FindNewPairs<b3ContactManager>(b3ContactManager * callback) Line 159
b3ContactManager::FindNewContacts() Line 159
b3World::Step(float dt, unsigned int velocityIterations, unsigned int positionIterations) Line 106
It happens at this call stack.
I don't understand the concept of proxy, but if proxyId is the index of an active node, why it should be less than m_nodeCount? Should it have been less than m_nodeCapacity instead?

**Comment by irlanrobson** [comment]
A proxy simple abstracts a collision shape in the broadphase collision detection interface. Thus is simple a node in the dynamic tree. 

As for the assert. You're correct. I'll apply a quick fix. Thanks for reporting.
