### ISSUE TITLE
Compile error on Linux

### ISSUE THREAD

**Issue by RicoP** [irlanrobson/bounce#31]
clang says 

`
contact_cluster.cpp
In file included from ../../external/bounce/src/bounce/dynamics/contacts/contact_cluster.cpp:19:
In file included from ../../external/bounce/include/bounce/dynamics/contacts/contact_cluster.h:23:
../../external/bounce/include/bounce/common/template/array.h:241:3: error: use of undeclared identifier 'Swap'
                Swap(other);
                ^
                this->
`

the project compiles fine under windows. I think Swap has trouble casting "const b3StackArray<T, N>&" to "const b3Array<T>&" even though b3StackArray inherits from b3Array. Maybe a explicit cast can solve this?

**Comment by Kazade** [comment]
It might need more than a cast, because `b3StackArray` has the extra `T m_stackElements[N];` member which presumably should also be swapped?

**Comment by Kazade** [comment]
Ah, ignore me, I see that is passed up in the constructor. Cast should do it.

**Comment by RicoP** [comment]
Actually it might be enough to just delete the overload of the operator= 

Works for me on windows.

**Comment by irlanrobson** [comment]
> Works for me on windows.

Did you mean on Linux?

There is no way I can test this project on Linux at the moment. Please if you find a tested solution to the problem, describe it on a comment, and send me a pull request. The users will appreciate very much :).

**Comment by Kazade** [comment]
This works: https://github.com/Kazade/bounce/commit/c722224b58bf6723f20527b35775121a949db5aa

I'll send a PR when I get a second :)

**Comment by Kazade** [comment]
Thanks! Sorry I didn't get to send a PR!

**Comment by irlanrobson** [comment]
No worries, Kazade!!
