### ISSUE TITLE
Question: How to lower the center of mass?

### ISSUE THREAD

**Issue by Kazade** [irlanrobson/bounce#5]
Sorry, I know I've asked this question before but I'm still having trouble. I have a working car physics system using bounce, and I'm trying to lower the COM so that the cars are self-righting and don't keep rolling over. I'm currently doing that like this:

```
    b3MassData data;
    body_->GetMassData(&data);
    data.center = new_com;
    body_->SetMassData(&data);
```

But this makes everything behave erratically; cars spin everywhere, they get stuck into the ground etc.

What am I doing wrong?

**Comment by irlanrobson** [comment]
Are you setting a local center of mass (COM)? SetMassData accepts the position of the COM relative to the body transform.

**Comment by Kazade** [comment]
Yeah, even setting something small (e.g. (0, -1, 0) ) results in really glitchy behaviour :(

**Comment by irlanrobson** [comment]
Try converting your world COM to local body space using, b3Body::GetLocalPoint. If this doesn't work I would need more time to investigate this. It might take a while, because I'm not in town currently.

**Comment by Kazade** [comment]
I tried, but that didn't make any difference - but I wouldn't expect it to because at the time I try to lower the center of mass the body is untransformed. Does the mass data `I` value need changing at the same time as the COM?

**Comment by irlanrobson** [comment]
Are you rendering the center of mass? Is it appearing at the expected location? 

IIRC SetMassData already shifts the given inertia to the provided local center of mass.

Does your body contain joints? Try to play with a body that doesn't contain any joint and see if you get the correct behaviour.

**Comment by irlanrobson** [comment]
If you are in a hurry and just want to get things working you could try adding another fixture to the bottom to lower the com. and disable collision with every other fixture against the balance fixture.

**Comment by Kazade** [comment]
The body contains no joints - it's simply a box with 4 downward ray casts. I'm not rendering the center of mass but I'll try that later. I'll also try the workaround with another fixture.

I'm now questioning if the erratic behaviour is related to how I'm playing the upward suspension force... I'm currently applying the upward force at the wheel impact point (in world space), I wonder if I'm doing something wrong there...

**Comment by irlanrobson** [comment]
b3Body has two functions for applying forces. For your case use ApplyForce given world point. This also creates a torque. The torque depends on the com. ApplyForceToCenter creates no torque as it applies a force to the com.

**Comment by Kazade** [comment]
Right thanks, I think I'm doing the right thing then.

**Comment by irlanrobson** [comment]
Also, make sure your force is in world space. You can convert from body local space to world space force using b3Body::GetWorldVector.

**Comment by irlanrobson** [comment]
You build a transform using GetOrientation and GetWorldCenter and render this transform. 

Also, if you are creating or destroying another fixture after setting the com. it will reset the body mass data and override your com. Create all your fixtures and then change the com.

I encourage you to run the Testbed and make a simple test or edit an existing one changing the center of mass and applying a force. There is an option there to render the transform. It could be a simple sync issue with your transform in your program. 

Make sure you're on Windows. I think I've forgotten putting Linux and Apple code to work.

**Comment by Kazade** [comment]
I'm on Linux, but I'll take a look at the testbed and submit a PR to get it to work if necessary :+1:

**Comment by irlanrobson** [comment]
You will need to include GLAD's GLX and modify the CMake list to include it if on Linux. There is another project called Bounce Softbody in my profile that has a compatible GLX sources in the external folder. Grab those and put it into Bounce.

**Comment by irlanrobson** [comment]
I highly recommend you to test code in the Testbed before implementing something in your engine while there is no user manual. You will do yourself a big favor using Testbed as a reference.

**Comment by Kazade** [comment]
OK I think the testbed shows the same issue. I changed the "capsule stack" test with the following patch: 

```
From 6a150700eb5749bdaf75ba1a784359bafba51040 Mon Sep 17 00:00:00 2001
From: Luke Benstead <kazade@gmail.com>
Date: Mon, 28 Feb 2022 20:15:47 +0000
Subject: [PATCH] Demonstrate center-of-mass issue

---
 examples/testbed/tests/capsule_stack.h | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/examples/testbed/tests/capsule_stack.h b/examples/testbed/tests/capsule_stack.h
index ec25e66..46a5b16 100644
--- a/examples/testbed/tests/capsule_stack.h
+++ b/examples/testbed/tests/capsule_stack.h
@@ -106,6 +106,11 @@ public:
 
 					body->CreateFixture(fd);
 
+					b3MassData data;
+					body->GetMassData(&data);
+					data.center = b3Vec3(2.0f, 0.0f, 0.0f);
+					body->SetMassData(&data);
+
 					u32 bodyIndex = GetBodyIndex(i, j, k);
 
 					m_bodies[bodyIndex] = body;
-- 
2.35.1

```

This moves the center of mass to the end of the cylinders - what happens when they hit the floor is the cylinder rotates in the opposite direction than you'd expect as it hits the ground - then everything spins off the screen.

![image](https://user-images.githubusercontent.com/16649/156052875-f34d88ee-44dd-4d1c-bf1e-792e32d19a24.png)

By the way, the only change I had to make to make the testbed work on Linux, was to add this macro at the top of the main.cpp file:

```
+#if defined(__linux__)
+/* sprintf_s is Windows specific */
+#define sprintf_s(buf, ...) snprintf((buf), sizeof(buf), __VA_ARGS__)
+#endif
+
```

Probably it would be a better fix to just use std::snprintf though on all platforms?

**Comment by Kazade** [comment]
Although now I think about it - that's not *quite* the same issue I'm having as I'm applying a force. I'll try to come up with a more accurate test of what I'm doing tomorrow.

**Comment by irlanrobson** [comment]
I think it might be a problem with the inertia tensor then. Can you verify if all stored inertia tensors and inverse are valid?

**Comment by irlanrobson** [comment]
Here's a quick thing I found in Box2D repository. 

"Yeah, the inertia in b2MassData is about the local origin. I recommend to first take the result from GetMassData and convert the inertia to the old center of mass.
Ic = I1 - m * dot(c1, c1)
Then compute the new inertia:
I2 = Ic + m * dot(c2, c2)
Then Box2D will find Ic correctly."

I'm not sure if this will work. In 3D the dot is replaced with b3Steiner. So basically you have:

b3MassData md;
body->GetMassData(&md);

// Shift to old center of mass
b3Mat33 Ic = md.I - md.mass * b3Steiner(md.center);

// Compute new inertia
b3Ma33 I2 = Ic + md.mass * b3Steiner(newCenter);

// Set mass data
md.center = newCenter;
md.I = I2;
body->SetMassData(&md);

Try this and see if it works.

**Comment by Kazade** [comment]
Thank you! I'll give that a try tomorrow and let you know how it goes.

**Comment by irlanrobson** [comment]
I just tested shifting the center of mass to old center and then to body origin like above and it works. The capsules don't spin erratically. When not shifting the inertia, it can becomes very small and the inverse negative. This will not work.

**Comment by Kazade** [comment]
So, that massively improves the situation, things are generally reacting as expected - but I'm still seeing very glitchy collisions:

![image](https://user-images.githubusercontent.com/16649/156147329-90d0a5ea-610a-459b-8930-c86bdaa48cef.png)

I'll try to recreate in the testbed later - but the cars are bodies with a single box collider and you can see how they seem to sink into the ground - this doesn't happen if I don't move the center of mass.

**Comment by irlanrobson** [comment]
How are you setting a box and center of mass? I tried creating a box with a shifted center of mass and inertia and I see no bug...

**Comment by irlanrobson** [comment]
Is the collision against a triangle mesh (terrain)?

**Comment by Kazade** [comment]
Yes it is! I also haven't been able to recreate the problem in the testbed

**Comment by irlanrobson** [comment]
Can you paste your setup here?

**Comment by Kazade** [comment]
Unfortunately it's not super easy to pull out the exact setup as everything is abstracted through the engine and game code. I'll try to come up with a test case over the next couple of days though.

It's almost certainly related to the suspension forces being applied at the 4 corners. What I'm seeing is either one side of the car sink, or the front or back sink - at times the whole car will fall through though. 

Anyway, leave it with me and I'll find time to come up with a test case.

**Comment by irlanrobson** [comment]
Okay. Let's leave this for the long term. I don't have much time to look this up, but if you come with a simple test case failing I definitely will reproduce this here.

**Comment by Kazade** [comment]
I just ran a quick test. If you use the mesh contact test, set the COM outside the hull/cube, enable the heightmap terrain and move the cube around quickly it will fall through the floor. I've repeated this with both flat + terrain.

**Comment by irlanrobson** [comment]
Does your test case work with a grid? It might be a mesh contact problem. I might look at this later.

**Comment by irlanrobson** [comment]
Here's a quick thing to try. Instead of using b3MeshShape create many b3TriangleShape for each triangle in the mesh. So we can check if this is a problem with a mesh contact.

**Comment by Kazade** [comment]
It's much much harder to trigger with a grid, I've only done it once. Quite easy to trigger with the terrain.

I'll try your suggestion later.

**Comment by irlanrobson** [comment]
Hey I tested a box with a terrain and saw no glitch. I've create a test called ShiftCenter in the Testbed. You can check it if you want to see how I did it.

**Comment by Kazade** [comment]
Thanks, I am able to recreate going through the terrain with that test (try to pull the cube through the floor and move it around).

This might not be the same issue that I'm seeing in the game though. I'm going to try what you suggested earlier by using triangle shapes instead of the mesh to see if anything changes.

**Comment by irlanrobson** [comment]
Hey Kazade, any news? Just remembering you to keep your code synchronized with the latest version of the library and see if anything changes... Did you run the ShiftCenter test? I didn't notice a bug...

**Comment by Kazade** [comment]
Sorry I got drawn into other parts of the game (networking :roll_eyes:) and just reverted the center of mass back to the original place.

Yes I managed to recreate the issue with the ShiftCentre test. Try to drag the cube through the terrain and it will occasionally fall through (although this *rarely* happens when it's a grid).

One possibility: does it happen when the center of mass is the other side of the colliding polygon? :man_shrugging:

**Comment by irlanrobson** [comment]
I dragged the box over the terrain and it didn't pass through it. Try to come up with a more focused example.

**Comment by irlanrobson** [comment]
Hi Kazade. Try getting the latest version of the library. I know is a pain in the but keeping in sync with the latest code, sorry! However, there are some critical changes. Mainly performance improvements, API, and some fixes. Maybe now your boxes won't fall through the terrain after these fixes. :P

**Comment by Kazade** [comment]
Thanks! I'll update and let you know how it goes :)

**Comment by Kazade** [comment]
Hmm, I'm having an issue while updating.

I have a test in my engine that makes sure my contact listener wrapper (around b3ContactListener) is working. This is the code from the unit test (obviously this is all engine code layered above Bounce, but you'll get the idea...)

```
        // Create a CollisionListener
        Listener listener(&enter_called, nullptr, &leave_called);

        // Create body A
        auto actor1 = stage->new_actor();
        auto body = actor1->new_behaviour<behaviours::StaticBody>(physics.get());
        body->add_box_collider(Vec3(1, 1, 1), behaviours::PhysicsMaterial::WOOD);
        body->register_collision_listener(&listener); // Register the listener

        // Create overlapping body B!
        auto actor2 = stage->new_actor();
        auto body2 = actor2->new_behaviour<behaviours::RigidBody>(physics.get());
        body2->add_box_collider(Vec3(1, 1, 1), behaviours::PhysicsMaterial::WOOD);

        // Run physics
        physics->fixed_update(1.0f / 60.0f);
        assert_true(enter_called);
        assert_false(leave_called);
```

This test has just started failing after updating, it must be one of today's commits because I updated Bounce only yesterday (or the day before?)

I'm not sure if it's a bug, or a change in behaviour. But essentially the engine is creating two overlapping bodies with unit-cube shapes and expecting the contact listener to fire when the second one is created.

**Comment by irlanrobson** [comment]
Now in a pair of bodies at least one body must be dynamic to collide. 

However this typically happens because contacts are created at the end of the time step but updated right in the next step. Did you try calling physics->physics_update twice?

**Comment by Kazade** [comment]
I've switched both to be dynamic, and calling update twice doesn't fix it :thinking: 

I'll keep debugging...

**Comment by irlanrobson** [comment]
Try to recreate it in the Testbed!

**Comment by irlanrobson** [comment]
I am trying to recreate this in the Testbed...

**Comment by irlanrobson** [comment]
I just tested it and it was a bug. I was not initializing a contact flag. Here goes my test: I am pushing a bugfix now.

```
class ListenerTest : public Test
{
public:
	ListenerTest()
	{
		m_enterCalled = false;
		m_leaveCalled = false;

		m_boxHull.SetExtents(1.0f, 1.0f, 1.0f);

		{
			b3BodyDef bd;
			b3Body* body = m_world.CreateBody(bd);

			b3HullShape hs;
			hs.m_hull = &m_boxHull;

			b3FixtureDef sd;
			sd.shape = &hs;
			sd.density = 0.2f;

			body->CreateFixture(sd);
		}
		{
			b3BodyDef bd;	
			bd.type = e_dynamicBody;
			b3Body* body = m_world.CreateBody(bd);
			
			b3HullShape hs;
			hs.m_hull = &m_boxHull;
			
			b3FixtureDef sd;
			sd.shape = &hs;
			sd.density = 0.2f;

			body->CreateFixture(sd);
		}

		m_world.Step(1.0f / 60.0f, 8, 2);

		B3_ASSERT(m_enterCalled == true);
		B3_ASSERT(m_leaveCalled == false);
	}

	void BeginContact(b3Contact* c)
	{
		m_enterCalled = true;
	}
	
	void EndContact(b3Contact* c)
	{
		m_leaveCalled = true;
	}

	static Test* Create()
	{
		return new ListenerTest();
	}

	b3BoxHull m_boxHull;
	bool m_enterCalled;
	bool m_leaveCalled;
};
```

**Comment by irlanrobson** [comment]
Also, you don't need to call a physics step twice. Call it once as you were doing! There is code that adds a flag to create new contacts at the beginning of a step if new fixture is added.

**Comment by Kazade** [comment]
Thank you! I'll update again tomorrow - I'm logging off now. I appreciate your help with this!

**Comment by irlanrobson** [comment]
You're welcome. I've applied the bugfix.

**Comment by Kazade** [comment]
OK all upgraded, but unfortunately the same problem persists; if I lower the center of mass the cars sink into the floor (and I just witnessed them sink into each other...)

When I get time I'll try to recreate the issue in the testbed.

**Comment by Kazade** [comment]
I can confirm though I see the same issue with triangle colliders, and the mesh collider... I'll do some more testing over the weekend.

**Comment by irlanrobson** [comment]
Okay, I will wait for your recreation then.

**Comment by Kazade** [comment]
I've just had a thought - it may not be anything to do with the collision detection. It's almost like the box collider orientation doesn't match the rigid body. The cars aren't falling through the ground - they continue to collide with things including the floor and walls of the stadium - but the rigid body "up" isn't matching the box "up". If I break the car free of the floor then it resets itself until the car hits the floor at a steep enough angle then it does it again.

**Comment by irlanrobson** [comment]
I'm not sure if I understand what you are saying. Try rendering the transforms. Try using a convex hull instead of the mesh and see if it works. This could be a mesh contact problem, although I see no problems in my test. Try transfering the same box properties you use in the game to the testbed. Unfortunately the best way for solving this problem is to minimalistically recreate the problem in the Testbed so I can step in the debugger.

**Comment by irlanrobson** [comment]
I've tried kind of matching the ShiftCenter test to what looks like in your image. I changed the box dimensions to match your car's and also scaled and rotated the terrain. The box collides normally with the terrain. I also lowered the center of mass. I tried dragging the box and it never passes through the terrain. The collision happens smoothly. 

Check if there is a problem when rendering the meshes in your game or when synchronizing the transforms. And again, if this doesn't work try reproducing your problem in the Testbed.

**Comment by Kazade** [comment]
Yeah I've been doing the same thing - and can't recreate the problem in the testbed.

I'll keep trying to figure out what the trigger is, the mesh is aligned with the rigid body rotation... maybe the problem lies with how I'm accessing that - perhaps I'm extracting the quaternion wrong or something.

**Comment by irlanrobson** [comment]
Maybe you can use b3Transform::GetTransformMatrix()? This converts the transform to a 4x4 matrix that you can use in OpenGL directly for instance because matrices use column major storage and column vectors.

**Comment by irlanrobson** [comment]
Generally you could implement a debug draw interface b3Draw, set to b3World, and call b3World::DebugDraw to draw the physics entities. That's easier and a pretty nice debugging feature.

**Comment by Kazade** [comment]
Aha! I've... sort of.. solved it!

```
-    auto position = b->GetWorldCenter();
-    auto rotation = b->GetOrientation();
+    auto position = b->GetTransform().translation;
+    auto rotation = b->GetTransform().rotation;
```

I was using GetWorldCenter, and GetOrientation to get the body position and rotation. Now... the weird thing is this. If I use GetWorldCenter, the car physics are fine, but I get the weird sinking issue, if I use `GetTransform().translation` the car physics are bouncy as hell, but the sinking issue is gone.

But, I think that's my problem again - nothing to do with Bounce.  Sorry to waste so much of your time!

**Comment by irlanrobson** [comment]
The body transform is used to transform the fixture shapes for rendering. For meshes you will also need to transform the mesh vertices by a scale applied in local space of the mesh. So for meshes the equation is:

worldVertex = transform * scale * localVertex

For hulls the equation is simply:

worldVertex = transform * localVertex

**Comment by irlanrobson** [comment]
No need to worry Kazade, these things happen. I'm glad I could help you. I hope you solve you bouncy issue soon.

**Comment by Kazade** [comment]
Yes, all solved. I was adding a force at a particular position - but that position was calculated relative to the WorldCenter so moving it made things super weird.

Thanks again for everything!
