### ISSUE TITLE
Incorrect position of the point when falling on the plane.

### ISSUE THREAD

**Issue by mrjbom** [irlanrobson/bounce#50]
I created a body that acts as the earth and a body that falls on it.
I have such variables for earth and body.
Gravity is directed at the -Y axis.

```
b3Body* groundBody;
b3BodyDef groundBodyDef;
b3BoxHull groundBodyBox;
b3Transform groundBodyTransform;
b3HullShape groundBodyShape;
b3ShapeDef groundBodyShapeDef;
b3Vec3 groundBodySize(100.0f, 1.0f, 100.0f);
b3Vec3 groundBodyPosition(0.0f, -1.0f, 0.0f);

b3Body* body;
b3BodyDef bodyDef;
b3BoxHull bodyBox;
b3Transform bodyTransform;
b3HullShape bodyShape;
b3ShapeDef bodyShapeDef;
b3Vec3 bodySize(1.0f, 1.0f, 1.0f);
b3Vec3 bodyPosition(0.0f, 10.0f, 0.0f);
```
I create the earth and the body in this way:
```
//ground
groundBodyDef.type = e_staticBody;
groundBodyDef.position.Set(groundBodyPosition.x, groundBodyPosition.y, groundBodyPosition.z);
groundBody = world->CreateBody(groundBodyDef);

groundBodyBox.SetIdentity();
//set halves
groundBodyBox.Set(groundBodySize.x / 2.0f, groundBodySize.y / 2.0f, groundBodySize.z / 2.0f);

groundBodyShape.m_hull = &groundBodyBox;
groundBodyShapeDef.shape = &groundBodyShape;
groundBodyShapeDef.density = 1.0f;
groundBody->CreateShape(groundBodyShapeDef);

//body
bodyDef.type = e_dynamicBody;
bodyDef.position.Set(bodyPosition.x, bodyPosition.y, bodyPosition.z);
body = world->CreateBody(bodyDef);

bodyBox.SetIdentity();
        //set halves
bodyBox.Set(bodySize.x / 2.0f, bodySize.y / 2.0f, bodySize.z / 2.0f);

bodyShape.m_hull = &bodyBox;
bodyShapeDef.shape = &bodyShape;
bodyShapeDef.density = 1.0f;
body->CreateShape(bodyShapeDef);
```

After running this program, I get the body height value equal to -0.005, this is not true.
The correct value is 0.5. After all, the distance to the center of the body size 1, will be 0.5.
Why does the library work with an error?

**Comment by irlanrobson** [comment]
This is not a bug in the library. It's a bug in your code.

`groundBodyBox` and `bodyBox` shouldn't be a temporary variables. b3BoxHull is a constant resource.

**Comment by mrjbom** [comment]
Understood. I made a global scope pointer to an object of type _b3BoxHull_ in this way:
```
b3BoxHull* groundBodyBox;
b3BoxHull* bodyBox;
```
Created object
```
groundBodyBox = new b3BoxHull();
bodyBox = new b3BoxHull();
```
But I still get the same results.

**Comment by irlanrobson** [comment]
I reproduced your code. By making both boxes a static variable I get the expected results with no problems.

**Comment by mrjbom** [comment]
I tried that. Here, look here, please.
I'm getting the wrong results.

```
#include <iostream>
#include <bounce/bounce.h>

using namespace std;

const u32 velocityIterations = 8;
const u32 positionIterations = 2;

constexpr auto frame_delay = 1.0f / 120.0f;

b3World* world;

b3Body* groundBody;
b3BodyDef groundBodyDef;
static b3BoxHull groundBodyBox;
b3Transform groundBodyTransform;
b3HullShape groundBodyShape;
b3ShapeDef groundBodyShapeDef;
b3Vec3 groundBodySize(100.0f, 1.0f, 100.0f);
b3Vec3 groundBodyPosition(0.0f, -1.0f, 0.0f);

b3Body* body;
b3BodyDef bodyDef;
static b3BoxHull bodyBox;
b3Transform bodyTransform;
b3HullShape bodyShape;
b3ShapeDef bodyShapeDef;
b3Vec3 bodySize(1.0f, 1.0f, 1.0f);
b3Vec3 bodyPosition(0.0f, 10.0f, 0.0f);

void b3BeginProfileScope(const char* name)
{

}

void b3EndProfileScope()
{

}

int main(int argc, char** argv)
{
	world = new b3World();
	const b3Vec3 gravity(0.0f, -9.81f, 0.0f);
	world->SetGravity(gravity);

	//ground
	groundBodyDef.type = e_staticBody;
	groundBodyDef.position.Set(groundBodyPosition.x, groundBodyPosition.y, groundBodyPosition.z);
	groundBody = world->CreateBody(groundBodyDef);

	groundBodyBox.SetIdentity();
	//set halves
	groundBodyBox.Set(groundBodySize.x / 2.0f, groundBodySize.y / 2.0f, groundBodySize.z / 2.0f);

	groundBodyShape.m_hull = &groundBodyBox;
	groundBodyShapeDef.shape = &groundBodyShape;
	groundBodyShapeDef.density = 1.0f;
	groundBody->CreateShape(groundBodyShapeDef);

	//body
	bodyDef.type = e_dynamicBody;
	bodyDef.position.Set(bodyPosition.x, bodyPosition.y, bodyPosition.z);
	body = world->CreateBody(bodyDef);

	bodyBox.SetIdentity();
	//set halves
	bodyBox.Set(bodySize.x / 2.0f, bodySize.y / 2.0f, bodySize.z / 2.0f);

	bodyShape.m_hull = &bodyBox;
	bodyShapeDef.shape = &bodyShape;
	bodyShapeDef.density = 1.0f;
	body->CreateShape(bodyShapeDef);

	for (int i = 0; 0 < 120; ++i)
	{
		cout << "body " << body->GetPosition().x << " " << body->GetPosition().y << " " << body->GetPosition().z << endl;
		world->Step(frame_delay, velocityIterations, positionIterations);
	}
	return 0;
}
```

**Comment by irlanrobson** [comment]
There is a typo in your code:

for (int i = 0; 0 < 120; ++i)

should be

for (int i = 0; **i** < 120; ++i)

Except this, I just run the code you gave me above and it works fine. The initial height of the body is 10. The final height of the body is 5.135877.

**Comment by mrjbom** [comment]
Why the program code above does not give the desired result?
And the final height of 5 is also not the right answer.

**Comment by mrjbom** [comment]
I think it looks like this and the result should be 0.5, but I get -0.005 and you get 5.
![Screenshot 19-08-2019 001134](https://user-images.githubusercontent.com/37502620/63230507-3bcefa00-c216-11e9-8e94-530f5e2cbd34.png)

**Comment by irlanrobson** [comment]
What you said is incorrect! Either is what you are drawing.

The initial height of the body was defined to 10 in the variable bodyPosition.

**Comment by mrjbom** [comment]
In the picture I depicted the very end of the program, the moment when the object falls to the ground and stop.
The initial height is 10, and the final one should be 0.5, the figure shows this.
So why am I not getting the expected result?

**Comment by irlanrobson** [comment]
I ran the code you gave me :

for (int i = 0; i < 120; ++i)

The final height of the body is 5.135877 at the time-step 120.

**Comment by irlanrobson** [comment]
I ran the code you gave me :

for (int i = 0; i < 120; ++i)

The final height of the body is 5.135877 at time-step number 120. 

This code doesn’t simulate enough time-steps for the box to fall on the ground at the end of its execution.

This code below:

for (int i = 0; i < 300; ++i)

performs 300 time-steps. This is enough for the box to fall over the ground. The final height of the body is -0.005 at time-step number 300. This is the expected result because Bounce allows some penetration to solve some instability problems. The allowed penetration value is B3_LINEAR_SLOP and it is defined in the configuration file settings.h. This value is set to 0.005 by default. Of course if you change this value to 0 and run the code above the height at the time-step number 300 will be 0.0, which is the real expected height. 

I think what you sketched is incorrect. Here’s a sketch of your simulation configuration at time-step number 300:

![reply](https://user-images.githubusercontent.com/4203641/63262639-dfdb9400-c25c-11e9-81a1-de6209885266.jpg)

**Comment by mrjbom** [comment]
Thank you very much for your help. I apologize for my mistake.

**Comment by irlanrobson** [comment]
No worries. I am here to help.
