### ISSUE TITLE
How to get the box size?

### ISSUE THREAD

**Issue by mrjbom** [irlanrobson/bounce#51]
Hello.
I need to get the box size on the X, Y and z axes.
I tried to get them using _b3BoxHull_ methods but found nothing.

And how can I control the elasticity of an object?

**Comment by irlanrobson** [comment]
> How do I get the box size?

I don't track the box extents inside b3BoxHull. You would need to maintain those values somewhere by yourself. That's easy to solve.

> And how can I control the elasticity of an object?

Rigid bodies are perfectly rigid objects. While you can control its coefficient of restitution, you can't control elasticity. However, you can control elasticity of a soft body (b3SoftBody) using Young modulus of elasticity and Poisson's ratio. 

You can use b3BlockSoftBodyMesh to easely setup a soft box. For examples, see the Beam test in the testbed.

**Comment by mrjbom** [comment]
Can I make body type _b3Body_ bounce when hitting another solid body?

**Comment by irlanrobson** [comment]
Yeah, usually you can do this by setting a coefficient of restitution for a shape. You can configure this value inside b3ShapeDef. 

For example, see the VaryingRestution test in the Testbed!!
