### ISSUE TITLE
Why can't I create a smart body pointer?

### ISSUE THREAD

**Issue by mrjbom** [irlanrobson/bounce#52]
Hello.
I created a vector of smart pointers shared_ptr on b3Body, and found that I can not create a link to them.
I don't know how to explain it, just look here.
```
	//ok
	int num = 10; 
	int* numPtr = &num;
	shared_ptr<int> sharedPtr;
	sharedPtr = shared_ptr<int>(&num);

	//error
	b3Body* testBodyPtr = world->CreateBody(*bodyDef[i]);
	shared_ptr<b3Body> sharedPtrToBody(testBodyPtr);
```
Do I have to use the usual pointers?

**Comment by irlanrobson** [comment]
I am not really familiar with smart pointers and all some of that modern C++ stuff at the moment but it isn't a good idea to copy b3World objects around if that's needed. None of b3World objects implement copy operators since they are managed by b3World.

**Comment by mrjbom** [comment]
Okay, I'll use the usual pointers to work on the bodies.
Thanks you.
