### ISSUE TITLE
b3MeshShape has no localScale parameter

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#54]
A typical use case in games is to instance thousands of times the same physics mesh, but with different transform and scale. 
Bounce currently doesn't support scaling for meshes, so all these meshes must be duplicated for each instance, which takes a large burden on memory and initialization speed.

Would it be possible to support non-uniform scaling for b3MeshShape?

**Comment by irlanrobson** [comment]
b3MeshShape is really for a static game level. Designers love to define static environment using tesselated triangle soups.

If you want to use multiple instances of the same object you should use b3HullShape. The associated convex hull will be simplified and likely consume way less memory than a mesh.

Non-uniform scaling can create some problems with the transforms inside the physics engine I think. I have never really implemented this. Most of the physics formulas involving transforms are well defined in terms of translation and rotation.

**Comment by fredUmlaut** [comment]
There is no real change needed to the underlying physics implementations. Only when processing the mesh vertices then each vertex must be multiplied with the scale. Everything else will happen then automatically.

Here for instance an example how to modify b3MeshShape::RayCast to support scaling
`
bool b3MeshShape::RayCast(b3RayCastOutput* output, const b3RayCastInput& input, const b3Transform& xf, u32 index) const
{
	B3_ASSERT(index < m_mesh->triangleCount);
	b3Triangle* triangle = m_mesh->triangles + index;
	
	b3Vec3 v1 = m_mesh->vertices[triangle->v1];
	b3Vec3 v2 = m_mesh->vertices[triangle->v2];
	b3Vec3 v3 = m_mesh->vertices[triangle->v3];

       v1*=m_scale;
       v2*=m_scale;
       v3*=m_scale;
`

Such non uniform scale is also supplied in other physics engines because level designers need often to scale meshes in a non uniform way.

**Comment by irlanrobson** [comment]
I see! Well, your code is doing uniform scale. (Scale by the same ammount along each canonical direction.)

That's a good idea. I probably haven't added it because the other shapes don't support scaling. For me this is inconsistent.

**Comment by irlanrobson** [comment]
Also, transforming the vertices is not enough. b3Mesh uses an AABB tree. There is more work.

**Comment by irlanrobson** [comment]
Now local non-uniform scaling for b3MeshShape shapes is implemented. Positive non-uniform scaling only.

Does that solve one of your problem?

**Comment by fredUmlaut** [comment]
Thanks a lot Irlan. That solves the problem. I tested your new update and it worked perfect!
