### ISSUE TITLE
b3MeshShape::ComputeAABB(b3AABB* output, const b3Transform& xf) computes shifted AABB when m_scale is used

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#57]
`b3MeshShape::ComputeAABB(b3AABB* output, const b3Transform& xf) const `
Computes the unscaled AABB with transform and then scales the lower/upper bound. 
This offsets the AABB wrongly.

b3AABB->Set would need to scale the vertices before applying the transformation like this:

`
	void b3AABB->Set(const b3Vec3* points, u32 count, const b3Transform& xf,const b3Vec3 &scale)
	{
		lowerBound = upperBound = b3Mul(xf, b3CWiseMul(scale,points[0]));
		for (u32 i = 1; i < count; ++i)
		{
			b3Vec3 v = b3Mul(xf, b3CWiseMul(scale,points[i]));
			lowerBound = b3Min(lowerBound, v);
			upperBound = b3Max(upperBound, v);
		}
	}
`

ComputeAABB must not anymore scale the lower/upper bound.

**Comment by irlanrobson** [comment]
I think you are right.

I probably used the following verification and forget to account to the transform. 

Say computing the AABB for three points:

lowerBound = b3Min(v1, b3Min(v2, v3))

Now you apply a non-uniform scale matrix S:

lowerBound = b3Min(S * v1, b3Min(S * v2, S * v3)) = 
lowerBound = S * b3Min(v1, b3Min(v2, v3))

This works for computing a local aabb.

If we take the transform into account the above doesn't hold anymore.

**Comment by irlanrobson** [comment]
Just applied a bufix. Closing this issue...
