### ISSUE TITLE
b3RayCastListener supports no filtering

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#58]
In games you typically cast rays for specific body types. To speed up operation you don't want that every contact is evaluated but only contacts with bodies you are interested in. Especially if costly triangle soups are evaluated, despite they are not needed for this ray cast.

Therefore it would increase performance in games a a lot when b3RayCastListener would have an option to support that. For instance:

virtual bool b3RayCastListener::needsCollision(b3Shape* shape);

This function would be called when Ray/AABB is checked and before evaluation is done on this Shape. If the user is not interested in this shape then he return false.

**Comment by irlanrobson** [comment]
How would I call such a feature? A ray-cast filter?

**Comment by irlanrobson** [comment]
Just commited a code to do what you described.

Now you will have to pass a ray-cast filter when performing a ray-cast on the world. See world_callbacks.h.

**Comment by fredUmlaut** [comment]
Sounds great. Thanks!
