### ISSUE TITLE
void b3CollideCache may generate no contact point and asserts therefore

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#59]
b3CollideCache may fail to generate a contact point. For that case there is this call at the end:

`
	// When both convex hulls are not simplified clipping might fail and create no contact points.
	// For example, when a hull contains tiny faces, coplanar faces, and/or non-sharped edges.
	// So we simply create a contact point between the segments.
	// The hulls might overlap, but is better than solving no contact points.
	b3BuildEdgeContact(manifold, xf1, edgeQuery.index1, s1, xf2, edgeQuery.index2, s2);
`

However, b3BuildEdgeContact may also fail and just return. Then no contact point is generated.

**Comment by irlanrobson** [comment]
This function may never fail. Two paralell edges don't build a separating axis at all. So I check if they are paralell inside the SAT code. 

However, I agree removing the assert is better since we it is in a world of floating point arithmetic.

**Comment by irlanrobson** [comment]
Fixed this in a new commit.
