### ISSUE TITLE
Minor compilation error "explicit qualification required to use member 'Copy' from dependent base class"

### ISSUE THREAD

**Issue by caxapexac** [irlanrobson/bounce#6]
C++ 17, emscripten

```
/common/template/array.h:246:3: error: explicit qualification required to use member 'Copy' from dependent base class
```

Solved by changing Line 246
from:
```cpp
Copy(other);
```
to
```cpp
this->Copy(other);
```

http://www.cs.technion.ac.il/users/yechiel/CS/FAQs/c++-faq/nondependent-name-lookup-members.html

**Comment by irlanrobson** [comment]
Do you have another alternative workaround to the this pointer? I'm not a big fan of the this pointer. Maybe using a namespace. 

Send a PR and I'l gladly merge it in.

**Comment by caxapexac** [comment]
Okay I'll do it a bit later

**Comment by irlanrobson** [comment]
I've applied a fix to this. Thanks for reporting.
