### ISSUE TITLE
b3Shape.m_scale should support negative scaling

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#60]
Currently the various b3Shape function assert for negative m_scale. As far as i can see there is no need to have such an assert because negative scaling works without issues. The physics engine doesn't care how the vertices are transformed. 

I think the only assert needed is that ALL axis are 0.0

**Comment by irlanrobson** [comment]
I use some functions for transforming between coordinate systems because I also use a static AABB tree as midphase structure. Those functions are well defined in terms of rotation, translation, and positive local scale. Not sure if that would work allowing a negative scale. So I conclude I am not going to spend one second on this. Positive scale should be sufficient.

**Comment by fredUmlaut** [comment]
Bullet (at least) supports negative scaled meshes and its commonly used in games (its needed for any symmetric level building, typically found in racing games for instance). 

For the AABB there won't be problems because its just transformed vertices to it. The negative scale is transparent for the AABB. There are no changes needed.

However, there may be issues if you extract normals or winding order from the triangles. If those are wrapped behind the b3Shape interface then its would be just a minor issue to support.

**Comment by irlanrobson** [comment]
I can remove the asserts if you want...

**Comment by irlanrobson** [comment]
> For the AABB there won't be problems because its just transformed vertices to it. The negative scale is transparent for the AABB. There are no changes needed.

That's not what I meant. I meant the functions for transforming a AABB from scaled space into unscaled space, not computing a AABB in scaled space.

**Comment by irlanrobson** [comment]
I have just added support for negative scaling as requested. This required few changes...

**Comment by fredUmlaut** [comment]
Wow, that's is really kind! Sorry for all the work i cause!

**Comment by irlanrobson** [comment]
No worries. That's a great type of contribution actually. :)
