### ISSUE TITLE
Always upright bodies are not possible (and also no '2D gameplay' constraints).

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#62]
When implementing a physics based character controller its vital that the avatar shape stands upright, no matter which forces are used against it. Using a constraint for this is no solution because there is no guarantee it will converge within a single frame.

A similar issue is happening when you want to restrict gameplay for your avatar to specific axis for a while (for instance limit movemement to the X/Y axis). Constraints are also no good solution for this.

Other physics engines solve that problem by having two parameters for each body:

b3Vec3 m_angularFactor
b3Vec3 m_linearFactor 

When impulses/forces are applied (regardless if its by the contact solver or user input) they are multiplied with these params like this (simplified, doesn't use mass properties):

`
void addLinearImpulse(b3Vec3 impulse ){
 m_linearVelocity += impulse * m_linearFactor ;
}
void applyTorqueImpulse(b3Vec3 torque)
{
 m_angularVelocity +=  torque * m_angularFactor;
}
`
So the forces never go into the constraint solver and no special code is needed anywhere else.

So for an 'always upright' avator the user needs only to set m_angularFactor(0,1,0).
For 2D gameplay the user would set m_linearFactor(1,1,0) and m_angularFactor(0,1,0).

It would be a great addition to Bounce to support this very game relevant features.

**Comment by irlanrobson** [comment]
Have you tried setting the following flags inside b3BodyDef?

fixedRotationX
fixedRotationY
fixedRotationZ

These flags can be used to constrain the rotation of the bodies along the canonical axes.

**Comment by fredUmlaut** [comment]
Thanks for the hint. I tried and it works!

Would it be possible to make this accessible when the body is already created? I see its stored in the flags but they cant be set afterwards..

What do you think about the linear constraint? Perhaps it can be added as a flag as well? This would be a big help.

**Comment by irlanrobson** [comment]
> Would it be possible to make this accessible when the body is already created? I see its stored in the flags but they cant be set afterwards..

Just added this to the library as requested.

**Comment by fredUmlaut** [comment]
Thanks Irlan!
