### ISSUE TITLE
There is no b3Body::SetTransform using a matrix

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#63]
Currently SetTransform can only be used with axis/angle parameters. In a game context you often use matrices to update a transform. It would be great if a 2nd SetTransform method could be added like this:
`
inline void b3Body::SetTransform(const b3Vec3& position, const b3Mat33 mat) 
{
	m_xf.position = position;
	m_xf.rotation = mat;

	m_sweep.worldCenter = b3Mul(m_xf, m_sweep.localCenter);
	m_sweep.orientation = b3Mat33Quat(mat);
	m_sweep.worldCenter0 = m_sweep.worldCenter;
	m_sweep.orientation0 = m_sweep.orientation;
	SynchronizeShapes();
}
`

A side benefit would be its also faster because no Quat->Matrix conversion is needed.

**Comment by irlanrobson** [comment]
I'll add this feature for convenience.

**Comment by fredUmlaut** [comment]
Thanks a lot.

**Comment by irlanrobson** [comment]
Now you can set the transform directly from a position and orientation quaternion/matrix. 

I removed setting the transform from axis and angle since you can always build the corresponding quaternion externally. This is more consistent and convenient.
