### ISSUE TITLE
QueryAABB has no filter support

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#64]
Currently you gather all AABBs with QueryAABB. After that step you need to filter it with a custom user filter to get only the AABBs you really want.
It would be good to extent this function with the same filter concept like b3RayCastFilter.
Perhaps it would make sense to simplify the b3RayCastFilter to a generic b3Filter. 
This b3Filter could then be used with any Cast/Querry function.

**Comment by irlanrobson** [comment]
AABB query is really fast. This is why I probably haven't implemented.  

Anyways, b3QueryFilter will be added for completeness. It might have its use cases.

**Comment by fredUmlaut** [comment]
Thanks!

**Comment by irlanrobson** [comment]
Feature added. Now you can control which shapes are reported to the listener using a query filter.
