### ISSUE TITLE
b3Body::SetLinearDamping has not vector input

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#66]
In most games you want to damp the x/z axis while the y (up) axis should not be damped.
Could you therefore please add a damping function that also takes a vector? Like this:

b3Body::SetLinearDamping(const b3Vec3 &damp)

**Comment by irlanrobson** [comment]
I'll take a look at this later. 

I am implementing a prismatic joint and might not have time to quickly add the features you are asking me right now.

**Comment by fredUmlaut** [comment]
Of course. 
Looking forward the new joint!

**Comment by irlanrobson** [comment]
I has already been added to the library. For example, see the PrismaticTest in TestBed. This joint is quite usefull.

**Comment by irlanrobson** [comment]
Good to go...
