### ISSUE TITLE
Sensors contacts don't have manifolds

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#68]
Sensors are good performance wise, but often you need also information where the contact happened, not just that a contact happened.

Bullet allow this behavior by having a body flag called 'No contact response'. When this flag is set on a body then its contacts are not used anymore in the solver, but they are still reported.

It would be great if Bounce could support this feature too.

**Comment by irlanrobson** [comment]
Adding flags can increase complexity so for the moment the library will be generating sensor contact manifolds, but not solving them obviously.

**Comment by fredUmlaut** [comment]
That's absolutely enough. Thanks a lot for the quick help!
