### ISSUE TITLE
By default all static bodies are set to active

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#69]
Not sure about performance implications. They seem to stay active forever.

**Comment by irlanrobson** [comment]
Body deactivation is not supported. 

I probably have included a flag in b3BodyDef indicating a future feature.

Do you need body activation/deactivation?

**Comment by irlanrobson** [comment]
I'll probably have a look at this feature later, okay? I am implementing a joint and might spend some time on this...

**Comment by fredUmlaut** [comment]
Of course, take your time!

I used the wrong words. I meant sleeping/awake with active.
I saw sleeping must be enabled on b3World. I was used to do this for each Body in Bullet, so didn't saw that.

However, deactivating bodies, so that they are no more used in simulation would be a good feature :)

So this is working for me then!
