### ISSUE TITLE
Shape has no SetSensor(bool enable) function

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#70]
Could you please add a SetSensor(bool enable) function to b3Shape to make this behavior dynamic?

**Comment by irlanrobson** [comment]
Yeah, that should be easy...

**Comment by irlanrobson** [comment]
This is already implemented. See b3Shape::SetSensor.

**Comment by fredUmlaut** [comment]
Sorry, looked at the wrong place!
