### ISSUE TITLE
There is no ::NeedsResponse(..) filter like b3ContactFilter::ShouldCollide(..)

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#71]
Like with b3ContactFilter::ShouldCollide() we also have a World::NeedResponse() function in our games. Bullet physics offers functionality this too.

This works much like the Sensors. When the NeedsResponse() function returns false then the contact won't get processed by the solver, but it is still available for the user.

This could just be a another b3ContactFilter:
b3World::SetNeedsResponseFilter(b3ContactFilter *filter);

It would be a big help if this could be supported with Bounce.

**Comment by irlanrobson** [comment]
I added a contact response filter inside b3ContactFilter.

Users can implement ShouldRespond function. This function returns true by default.

**Comment by fredUmlaut** [comment]
Awesome! Thanks again!
