### ISSUE TITLE
Body can't control sleep behavior

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#72]
Could you please support to toggle sleeping behavior for each Body?
Currently only fixed constants are available.

Bullet and Physx allow to determine linear/angular sleep thresholds and 
time thresholds to modify sleeping for your games needs.

So a minimum awake time could be specified, where <0 would mean forever. Like this:
b3Body::SetMinimumAwakeTime(float t)

If this is too much work currently then something like 
b3Body::EnableSleeping(bool enable) 
would already be a big help.

**Comment by irlanrobson** [comment]
Inside settings.h you can control these values globally:

B3_TIME_TO_SLEEP
B3_SLEEP_LINEAR_TOL
B3_SLEEP_ANGULAR_TOL

**Comment by fredUmlaut** [comment]
These constants work fine.
But i would need to toggle sleep processing on/off for each body. So that some bodies will never fall asleep.

**Comment by irlanrobson** [comment]
Oh, I quick scanned through your first post, sorry.

Yeah, I'll switch from global sleeping parameters to local parameters.

**Comment by fredUmlaut** [comment]
Thanks Irlan!

**Comment by irlanrobson** [comment]
Now you can control the linear and angular sleeping tolerances inside b3BodyDef and b3Body.

You can allow/disallow a body to sleep automaticaly inside b3BodyDef through a boolean and inside b3Body through a function.

**Comment by fredUmlaut** [comment]
Wow, you are super fast! Thanks!

**Comment by irlanrobson** [comment]
That one was easy to add. (:
