### ISSUE TITLE
Dynamic b3HullShape falls through static negatively scaled b3HullShape

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#75]
Create a dynamic b3HullShape>SetCylinder()
Create a static b3BoxHull. Set scale of this box to -1,1,1.
If the scale on the static is negative then the dynamic falls through.

Note:
A dynamic b3CapsuleShape (instead of the b3HullShape Cylinder) won't fall through.

**Comment by irlanrobson** [comment]
b3Hull supports only positive scaling. It should be adjusted to support negative scale too. 

I'll take a look at this...

**Comment by fredUmlaut** [comment]
I meant of course b3BoxHull and not b3Hull. I fixed the topic.
However, there is no real problem, because it doesn't make sense to scale a box negatively, as it still
will have the same shape. I just used abs() for the scale and everything is fine.

**Comment by irlanrobson** [comment]
I meant b3BoxHull. 

Fixing this should be easy though.

**Comment by fredUmlaut** [comment]
Nice :)
