### ISSUE TITLE
b3Island::Solve may do unecessary work on static bodies

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#77]
Is it necessary to iterate over static bodies in b3Island::Solve in these code blocks?

// 1. Integrate velocities
// 4. Integrate positions
// 6. Copy state buffers back to the bodies

**Comment by irlanrobson** [comment]
No. Static bodies are used inside the constraint solvers.

Of course in a game you would have a separate list of static/kinematic/dynamic bodies. This way you can avoid filtering bodies by type all the time.

**Comment by fredUmlaut** [comment]
I would suggest using more conditionals like your already do in "1." for non dynamics. 
As in games you usually deal with lots of static and few dynamics it would improve performance when solving the islands.

**Comment by irlanrobson** [comment]
I've just added some code that skips velocity integration if the body is static.

**Comment by fredUmlaut** [comment]
Thanks!
