### ISSUE TITLE
Contacts reported by b3ContactListener::PreSolve can't be fully modified

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#78]
To have better contacts for a physics based character controller i use PreSolve(contact) to modify the contacts. It changes the normal and the normalDepth if needed. 
However, the modified normalDepth may get later overriden here:
`
b3ContactSolver::SolveVelocityConstraints()
{

..
vcp->normalImpulse = b3Max(vcp->normalImpulse + impulse, 0.0f);
}
`

Perhaps contact manifold points could be flagged by the user to be not modified anymore?

**Comment by irlanrobson** [comment]
How did you accomplished what you need with the engines you were using?

**Comment by fredUmlaut** [comment]
For Bullet:

- In the gContactProcessedCallback I look at the contactPoint.m_lifeTime, the normal and the relative position of the contact point. From these info i reject contacts that look like edge collisions (in Bullet you can make manifold points invalid by setting p.m_distance1 = 1.0). 

Here I also implement 'stepping'. So the body does not get stuck when hitting low height geometry.
If i receive a contact that would block the body i make a shape cast from the top to where the body would normally be without being blocked. If this cast is successful then i modify the contact so that the character will move over that blocking geometry.

When the character was standing on slopes i also modified the contact so that the body was not sliding down by adjusting the normal.

For all(!) dynamic objects i also needed to remove the internal edge contacts, otherwise the quality of simulation was much to low on triangle soups. I made it like this:
- In the 'gContactAddedCallback' I used btAdjustInternalEdgeContacts to filter out unwanted internal triangle edge collisions. The triangle meshes needed a preprocess pass to get connectivity information.
So my character controller shape (a Cylinder shape) was able to glide smoothly over most triangle soups.

In Bounce i use a convex hull with the build-in Cylinder shape.

**Comment by irlanrobson** [comment]
List of things you need:

1. Contact point activation and deactivation
2. Contact normal modification

Anything else? 

I think you can already change some contact information outside. If not, this should be easy to implement. You can find a good example of this in the ConveryorBelt test in the Testbed.

**Comment by fredUmlaut** [comment]
1. Yes, tho i'm not sure what deactivate means in Bounce. Such a deactivated contact should be discarded and no more cached.

2. Yes, Normal and Contact depth. 

3. This contact must not be later overiden by  b3ContactSolver::SolveVelocityConstraints()

> I think you can already change some contact information outside. If not, this should be easy to implement. You can find a good example of this in the ConveryorBelt test in the Testbed.

Yeah!

Thanks!

**Comment by irlanrobson** [comment]
You are already able to change the separation/penetration and the normal. 

This seems to be difficult the way the contact information is stored in Bounce but it is actually pretty easy! I'll show you how you can do this. If you are familiar with vectors and points this will not be a difficult work.

The normal is stored in the space of body A. The normal is a vector. Therefore, you can transform it to the world space by multiplying it with the rotation of the body A (the linear transform that transforms vectors from body A's space to world space). In world coordinates you can change the normal, and convert it back to local coordinates of body A by multiplying the world normal with the transpose rotation of the body A (the linear transform that transforms vectors from world space to body A's space) and store this inside the manifold. 

You can use the same idea for changing the separation. Thus, it is derived from local contact points. Therefore, the separation can be changed by shifting the contact points along the normal to increase or decrease the separation. Of course you must map the contact points back to body coordinates to store inside the manifold.

This is how the normal and separation is computed for a contact point stored in body coordinates without the shape radius applied (manifold.cpp):

```
// Convert the contact points and normal to world coordinates
b3Vec3 nA = b3Mul(xfA.rotation, p->localNormal1);
b3Vec3 cA = xfA * p->localPoint1;
b3Vec3 cB = xfB * p->localPoint2;

// Compute the contact points in the surface of both shapes with radius applied
b3Vec3 pA = cA + rA * nA;
b3Vec3 pB = cB - rB * nA;
	
// Compute the separation
scalar separation = b3Dot(cB - cA, nA) - rA - rB;

// Change the normal and shift the contact points to change the separation
...

// Convert what you changed back to local coordinates and overwrite the manifold point
p->localNormal1 = b3MulC(xfA.rotation, nA);

p->localPoint1 = b3MulT(xfA, cA);
p->localPoint2 = b3MulT(xfB, cB);

```
Below rA and rB are the radius of the shapes in the contact. xfA and xfB are the transforms of the associated bodies.

You can easely visualize if you sketch this in a piece of paper!

**Comment by irlanrobson** [comment]
Practically activation or deactivation can be implemented storing a flag inside the contact point telling the contact solver to not solve the contact point. 

It seems you need to remove contact points from the manifold though. That's easy Manfred! It can even be done externally because users have write access to a manifold. Contact points are temporary so this can be done without breaking things. You will have to write an ordinary function to remove a element from an array.

**Comment by irlanrobson** [comment]
You will need to take care when you remove all contact points. In this case the contact must be flagged as non overlapped. Only overlapped contacts are sent to the contact solver.
