### ISSUE TITLE
b3Joints only works with two bodies

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#79]
I think this applies to all joints. 'Bounce Joints' work always with two bodies,
while other physics engines like Physx and Bullet support joints with only a single body.

In games you rarely need to connect two bodies but most often 
have a single body which is constraint to the worldspace frame of reference.

Here is the description of this feature from the Physx docs if the 2nd Body is NULL:
"Use a NULL pointer here to indicate an implicit actor representing the immovable global reference frame."

A simple solution would be to assign internally a dummy when bodyB is NULL, so most of the joint code must not be changed at all. A single dummy object for all joints should be sufficient.

**Comment by irlanrobson** [comment]
You can always create a body positioned at the world origin and aligned with the world frame and pass this as the first body in the joint. I call this the ground body.

**Comment by irlanrobson** [comment]
The ground body does not need to have a shape.

**Comment by fredUmlaut** [comment]
I see. Thanks for the information that it needs no shape.
