### ISSUE TITLE
Vec2/3/4 class extra?

### ISSUE THREAD

**Issue by caxapexac** [irlanrobson/bounce#8]
I mean B3_VEC3_CLASS_EXTRA in `user_settings.h` like in https://github.com/ocornut/imgui/blob/master/imconfig.h#L85
For vec2, vec3, vec4, transform and quaternion implicit convertion in client code

**Comment by irlanrobson** [comment]
I think all this stuff makes my code non-portable. Hence  I'm not doing it. Prefer writing functions for converting between these structures.
