### ISSUE TITLE
b3RevoluteJoint: Mass of a body slows down rotation 

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#81]
I created a b3RevoluteJoint between a dynamic and a static body around axis vec(1,0,0) . 
When the dynamic body is exposed to gravity it will swing realistically.

When i change the default mass from 1.0 to 0.1 the rotation slows down a lot.
Mass should not affect this motion.

The issue seems to arise from the use of b3RevoluteJoint.m_linearMass which 
damps linear movement to inverse of mass.

**Comment by irlanrobson** [comment]
> The issue seems to arise from the use of b3RevoluteJoint.m_linearMass which

> damps linear movement to inverse of mass.

This is not a problem with the linear mass. Bounce sub-solves the linear constraint exactly. No approximation.

This is a common problem. The iterative solver can have problems with large mass ratios. So it's recommended for you to balance the masses. 

Now for angular motion: 

I recently switched over from quaternion constraints to a different type of constraints for some joints because the involving formulas are simpler. We still have the advantage of recovering from very bad configurations.

From small multiplication involving the matrices of the quaternion constraints I was operating on very small values and it's well known floating point arithmetic is not so good at these. 

As the new angular solvers are more like an approximation, this can slow down the rotational correction a little but it should converge to a solution in a few frames without problems.

**Comment by irlanrobson** [comment]
If you insist in having large mass ratios you might consider using soft joints since damping can make the system more stable. These are the joints that currently support softness in Bounce:

b3WeldJoint
b3SpringJoint
b3WheelJoint
b3MouseJoint

Bounce doesn't support soft contacts! But they are recommended for large mass ratios too.

**Comment by fredUmlaut** [comment]
I understand. It's certainly not easy to make the joint behave similar for different mass setups.

I looked at the code and only the linear constraint is slowing down the simulation.
The angular constraint isn't using the inverse mass.

I made a few test for a body that swings 180 degree on a revolute joint.
I measured in frames how long it took until the maximum offset on the z axis is reached
(it swings around the x axis).

Here are the results for different mass:

| Mass        | Max Offset| Frames|
| ------------- |:-------------:| -----:|
| 4.0      | 3.37 | 27 |
| 2.0      | 3.37 | 30 |
| 1.0      | 3.36 | 34 |
| 0.5      | 3.39 | 42 |
| 0.25    | 3.28 | 53 |

The maximum offset is always very similar between a mass of 4.0 and 0.25. That's very good!
However, the frame time diverges a lot. It makes the mass=0.25 version feel like paper, compared to the mass=1.0 version. 

This makes it hard to simulate lighter stuff that is constrained and can be pushed around easily by a player character. Such bodies currently feel like moving in honey :)

**Comment by irlanrobson** [comment]
Now the sub position solver prioritizes the linear constraints by solving them by last. Maybe this can help.

**Comment by fredUmlaut** [comment]
Thanks for the change. 
I tested with the same parameters but the results were identical.

I understand that you aim for stabilization of the joint solver by using the invMass but this
introduces unrealistic damping for my test cases.

Perhaps this issue can be solved like this:

When i change in 'b3RevoluteJoint::InitializeConstraints' 

  m_mA = m_bodyA->m_invMass;
  m_mB = m_bodyB->m_invMass;

to

  m_mA = 1.0;
  m_mB = 1.0;

then the joint behaves like i expect (when compared to real life or Bullet).
The mass no more influences the damping and interactions with bodies feel natural.

To still have your stabilization code available you could introduce a new
'm_stability' parameter and lerp like this:
`
void b3RevoluteJoint::InitializeConstraints(const b3SolverData* data)
{
...

	m_mA = lerp(1.0, m_bodyA->m_invMass, m_stability);
	m_mB = lerp(1.0, m_bodyB->m_invMass, m_stability);
}
`
So we could have best of both worlds.

**Comment by irlanrobson** [comment]
That wouldn't be a good idea since it can introduce artificial linear energy into the system.

Also, you can already modify the mass properties of a body.

**Comment by fredUmlaut** [comment]
I see. Though it should be considered that the current implementation already artificially increases/decreases damping when mass!=1.0. 

This looks like a trade-off to me. With the 'm_stability' property the user could decide what trade off  is better for his simulation. Otherwise he is stuck with unrealistic highly damped constraints.

Perhaps your current approach should be linked to the mass ratio between the two bodies instead of the inverse mass of each body. So there would also be no extra damping when a body is constrained to a static body.

> Also, you can already modify the mass properties of a body.

I don't think its a good idea to change the mass of objects when they are constraint to make
the constraint work. Interactions with other bodies would also no more work as before because of the mass change.

**Comment by irlanrobson** [comment]
The revolute joint is neither damped nor softened. There is not extra damping!

Change the mass is not a good idea. But you can set a fairly reasonable initial density so that the mass of the objects are balanced.

**Comment by fredUmlaut** [comment]
Sorry for using the term damping. With damping i mean that the b3RevoluteJoint 
multiplies (more or less ) the linear impulse with the inverse mass here:

b3RevoluteJoint::SolveVelocityConstraints{
...
b3Vec3 impulse = m_linearMass.Solve(-Cdot);
}

In the simulation it then looks like a damping for the constraint impulse forces.

> Change the mass is not a good idea. But you can set a fairly reasonable initial density so that the mass of the objects are balanced.

I'm not sure if tuning masses/density should be the default solution to make a constraint work under such conditions.
Also Interactions with other bodies would also no more work like unconstrained because of the mass/density change.

**Comment by irlanrobson** [comment]
That portion of code is just solving a simple linear system that will output the impulse that will bring the relative velocities of the anchors points to zero. There is no damping. As I said earlier softness (which adds some damping in constraint space) is only supported for some types of joints. Although any joint can be softened.

If balancing the masses is not an option for you can try passing more constraint solver iterations to the time-step function b3World::Step.

**Comment by fredUmlaut** [comment]
> If balancing the masses is not an option for you can try passing more constraint solver iterations to the time-step function b3World::Step.

I increased the steps from 10 to 40 but there is no difference. I also don't think that increasing iterations has an effect in this case.

In my case i use this joint for a swinging door. The player can simply walk through it (like with a saloon door). In Bullet i used the Hinge constraint for that. There i set a low mass for the door body so that the player could easily walk through this door.

With Bounce i currently can't create a constraint that behaves similar. 
Either i give my door body a low mass, and the player can walk easily through it, but then the door swings back in slow motion.
Or i give it high mass and the swinging motion looks fine, but the player can't push the door anymore because its too heavy.

With my proposed 'm_stability' change the joint can be tweaked to support this behavior. 
I guess this behavior is also what most other developers are looking for when using the joint.
I would be very thankful if you could consider it.

**Comment by irlanrobson** [comment]
Can you paste here how you create the bodies connected by this revolute joint?

**Comment by irlanrobson** [comment]
Did you solve this problem?

> Would it be an option let size out of density calculations on demand, or to normalize it?

I am not sure I understand the question above.

PS: If you find troubles with chains of revolute joints I can restore the quaternion constraints anytime. I derived and implemented them correctly in the past. As I told you earlier I switched over to a more compact constraint that it is not as stable as a pure quaternion constraint but gives realistic results and it was simpler to implement and carry around. This is the best I can do with the current solver.

**Comment by fredUmlaut** [comment]
My problem is solved. Thanks.

> I am not sure I understand the question above.

In mean that in Bounce you don't let the user directly determine the mass/density of an body but you 
calculate it automatically regarding to its dimensions in functions like this:
b3SphereShape::ComputeMass...
This is nice but often unwanted. Other physics engines let simply set the user the mass, because of gameplay needs without to worry that gameplay will break when a body gets scaled slightly bigger.

So it would be cool if you could give the option not to relate the mass/density to the actual size of an body. Currently this isn't possible. When i tried to set the mass myself with b3Body::SetMassData(const b3MassData* data) then the b3RevoluteJoing broke for me, as described above.

**Comment by irlanrobson** [comment]
Please close the issue if you already solved the problem.

Yes, that's possible. As you pointed out correctly, users are already able to set the mass properties. It doesn't matter if you're setting the mass through the body definition or after it is created. 

This problem occurs due to a solver or a joint limitation probably. Currently joints that belong to a chain of joints are hard to recover from large positional errors. The same can be true for joints whose bodies correspond to a large mass ratio. 

Make sure your filling up the mass data with a reasonable inertia tensor. Try to reduce the mass or inertia gradatively to have a better notion of the limitations.

**Comment by fredUmlaut** [comment]
> Make sure your filling up the mass data with a reasonable inertia tensor. Try to reduce the mass or inertia gradatively to have a better notion of the limitations.

To set me own mass i called b3Body::SetMassData with 

b3Vec3 center //(0,0,0)
float32 mass //0.5;
b3Mat33 I; //Identity 

This destabilized the joint. So it seems calling "SetMassData" is not enough.
I think its one of the members that get evaluated by ResetMass() that is missing.
What needs to be done to set a 'reasonable inertia tensor'?

**Comment by irlanrobson** [comment]
I meant you should try to balance the intertia tensors too.
