### ISSUE TITLE
bounce.h includes time.h, but its not needed.

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#83]
"bounce.h" includes "time.h" which includes "windows.h" when Win32 is defined.

This increases compile time and leads to other problems caused by defines in "windows.h".

It would be great if you would not include "time.h" from "bullet.h" as its only needed with profiling (where "time.h" is included anyway)

**Comment by irlanrobson** [comment]
There are certainly some unecessary header inclusions in some files. 

I didn't have time for verifiying them all. But since time.h includes platform dependent code it might make sense removing.

**Comment by fredUmlaut** [comment]
Thanks. Compile issues is the only reason for me too.
