### ISSUE TITLE
b3WeldJoint doesn't allow to change anchor/rotation after creation

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#84]
Could you please provide methods to change LocalAnchorA/LocalAnchorB/Rotation after setup?

**Comment by irlanrobson** [comment]
Isn't destroying and recreating the joint with the new local anchors and frames fast enough?

**Comment by fredUmlaut** [comment]
I'm sorry, destroying joints for changing local frames would be no solution for my project :(

It looks to me that b3WeldJoint::SolvePositionConstraints already recomputes the inputs 
each iteration. So making 

	b3Vec3 m_localAnchorA;
	b3Vec3 m_localAnchorB;
	b3Quat m_referenceRotation;

public would be a solution for me.

**Comment by fredUmlaut** [comment]
I tested the above suggestion (changing the parameters at run time) in our game and it work flawlessly.
I would be thankful if would consider to make these variables accessible from the outside. That would be a big help!

**Comment by irlanrobson** [comment]
Glad it worked nice. 

Notice a weld joint can be softened. This can be usefull for large mass ratios. You can enable/disable softness at run time by setting the frequency to zero.

Do you mean acessing all the parameters for reading and writing as well or just reading?

**Comment by fredUmlaut** [comment]
Thanks for the info!

> Do you mean acessing all the parameters for reading and writing as well or just reading?

I mean for writing. For reading there are already accessors. So you could remove the const and make them return a reference.

**Comment by irlanrobson** [comment]
I can add a function to set from an anchor point after the joint is created.

**Comment by irlanrobson** [comment]
Use b3WeldJoint::SetAnchor() for changing the anchor point.

**Comment by fredUmlaut** [comment]
Excellent! Thanks
