### ISSUE TITLE
There is no b3World->ConvexCast(...) available.

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#85]
There is a gjk cast available, but no generic convex shape cast that can operate on the world.

**Comment by irlanrobson** [comment]
A convex cast function has been added to the world. 

Please if you find any bug report it, don't be shy.

**Comment by fredUmlaut** [comment]
Wow, excellent! Thanks a lot for adding it! I will bug test it.

**Comment by irlanrobson** [comment]
Convex cast inside the world performs a linear cast without considering angular motion of the shapes. The world shapes are treated as stationary to be consistent with ray-casting. 

The provided displacement is a vector typically coming from the transform position of the shape body.

b3TimeOfImpact already solves the TOI really fast. But making them static and linear allows some broadphase optimizations. You will are probably disabling character rotation for a dynamic/kinematic character controller and therefore this should be sufficient to your needs. 

However, the convex cast might have a possible small performance slow down when casting against a mesh shape. You of course can filter against unwanted shapes providing filters!

If you ever need to get the TOI considering angular motion there is a second more generalistic function that can be used externally. 

These functions are called b3TimefOfImpact and they reside in collision/time_of_impact.h. 

I tested both functions with a couple of sweeps and both work fine.

If you have any questions regarding how to use those functions please ask here!

**Comment by fredUmlaut** [comment]
Thanks Irlan for the internals. 

> Convex cast inside the world performs a linear cast without considering angular motion of the shapes. The world shapes are treated as stationary to be consistent with ray-casting.

So only the initial rotation of the shapes is used but no motion is interpolated along the cast, right? 
That is fine!

> However, the convex cast might have a possible small performance slow down when casting against a mesh shape. You of course can filter against unwanted shapes providing filters!

In Bulllet the ConvexCast had a noticeable slowdown with meshes. I will profile them against each other to get a better understanding of the performance.

Thanks again for your great work!

**Comment by irlanrobson** [comment]
Yes, only the rotation of the given shape stored inside the shape transformation and the current rotation of the world shapes are used.

Thanks, Manfred.

**Comment by irlanrobson** [comment]
For example, check out this test:

https://github.com/irlanrobson/bounce/blob/master/examples/testbed/tests/linear_time_of_impact.h
