### ISSUE TITLE
Testbed: Calling "Table Cloth" and then choosing another test will abort() in Debug Version

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#87]
because of memory leaks.

**Comment by irlanrobson** [comment]
On which platform is the testbed being executed? 

I can't find the memory leaks you are mentioning on Windows. 

You can use functions below to debug hard-to-find memory leaks at run-time

`
_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF | _CrtSetDbgFlag(_CRTDBG_REPORT_FLAG));`

and of course

`
_CrtSetBreakAlloc(...);`

**Comment by fredUmlaut** [comment]
My fault, it was the same issue i had yesterday, when not setting the right path. Sorry for bothering.
