### ISSUE TITLE
Collision matrix implementation

### ISSUE THREAD

**Issue by caxapexac** [irlanrobson/bounce#9]
Is there any example of implementing optimized collision masks/matrices based on b3*Filter?

I think I need public api like
```cpp
enum class layer
{
    Player = 0,
    Obstacle = 1,
    Transparent = 2
    // 3,4.5.... this isn't a bitmask
}

worldWrapper.setCollision(layer::Player, layer::Obstacle, true); // By default all collisions are disabled
bodyWrapper.addFixture(definition, scale, layer::Player);

class CustomXxxxxxxFilter : public b3XxxxxxxFilter
        {
        public:
            virtual bool ShouldRayCast(b3Fixture* fixture)
            {
                // What to do here?
            }
        };

```

*I've implemented something like this in the last library I've switched from (https://github.com/DanielChappuis/reactphysics3d) (switched cuz it doesn't have any shapeCast):*

```cpp

// collisionLayer = [0..15]
typedef unsigned char collisionLayer;

struct collisionMask
{
public:
    static const collisionMask all;

    unsigned short value = 0;

    collisionMask (std::initializer_list<collisionLayer> layers)
    {
        for (int i: layers)
        {
            ASSERT(i >= 0 && i < 16);
            value |= 1 << i;
        }
    }

private:
    collisionMask (unsigned short mask) : value(mask) { }
};

class worldWrapper {
// ...
    void setEnabledCollision (collisionLayer layer1, collisionLayer layer2, bool state)
    {
        ASSERT(layer1 >= 0 && layer1 < 16);
        ASSERT(layer2 >= 0 && layer2 < 16);
        unsigned short layer1Value = 1 << layer1;
        unsigned short layer2Value = 1 << layer2;
        unsigned short firstMask = m_collisionMatrix[layer1];
        firstMask ^= firstMask & layer2Value;
        firstMask |= state ? layer2Value : 0;
        m_collisionMatrix[layer1] = firstMask;
        unsigned short secondMask = m_collisionMatrix[layer2];
        secondMask ^= secondMask & layer1Value;
        secondMask |= state ? layer1Value : 0;
        m_collisionMatrix[layer2] = secondMask;
    }

    // Layer = [0..15]
    void setColliderLayer (rp::Collider* collider, collisionLayer layer)
    {
        ASSERT(layer >= 0 && layer < 16);
        unsigned short layerValue = 1 << layer;
        collider->setCollisionCategoryBits(layerValue);
        collider->setCollideWithMaskBits(m_collisionMatrix[layer]);
    }
// ...
}

```

But that library has setCollisionCategoryBits and setCollideWithMaskBits (and its pretty ugly tbh) so I have to use Fixture::userData here for storing these bits (or storing global `std::map<Fixture, layer>` inside the worldWrapper)

Also I think its a bit unflexible so looking for another solution

**Comment by irlanrobson** [comment]
Yeah, that sounds correct. 

ShouldRespond is to tell the world to wether or not create a contact (and that includes getting notified). ShouldRespond is about applying the collision response to the bodies in a existing contact.

**Comment by irlanrobson** [comment]
Now to your first question. Take a look at Box2D. Erin (the author) implemented what should probably be implemented in Bounce as well. I haven't done it for simplicity. Maybe in the future. Perhaps you can do something similar to collision masks with categories using the shape user data pointer.

**Comment by irlanrobson** [comment]
For now the only way to filter the collision between two fixtures is using the callbacks ShouldCollide/Respond.

**Comment by caxapexac** [comment]
Got it, thanks!
