### ISSUE TITLE
Ensure CCW cluster polygon

### ISSUE THREAD

**Issue by irlanrobson** [irlanrobson/bounce#9]
When reducing a cluster polygon whose points are originally ordered CCW due to the Sutherland-Hodgman clipping algorithm, the output points are not ensured to be in the same order. A simple fix to this issue is to pass the cluster normal as input to the reduction algorithm so it ensures the correct order in place.

**Comment by RandyGaul** [comment]
Why aren't output points still in CCW order? I read Sutherland-Hodgman was defined to preserve ordering.

**Comment by irlanrobson** [comment]
Sutherland-Hodgman is defined to preserve ordering. The output of the **reduction** code currently implemented doesn't ensure the points are always ordered CCW. This seems inconsistent. 

I had forgotten Dirk's Contact Creation talk for a while when I implemented the reduction code. Just read it over and am using his strategy for reducing the number of points. Since the normal is defined ahead, there is no need to use barycentric coordinates for finding the largest triangle area.

**Comment by irlanrobson** [comment]
As you know, just remembering the triangle area is 

a = 0.5 * dot( cross(e1, e2), n )

If we guarantee the first triangle is CCW, then the second chosen point and the edge e1 must form a CW triangle **and** maximize area. Otherwise the manifold is not well defined.

**Comment by RandyGaul** [comment]
I think youre analysis is all correct, but one more thing is it seems reduction code can be made to output CCW consistently. I implemented this all here: https://bitbucket.org/rgaul/lm/src/806fe4427db32f98e514c646b51f99ce1cfc5c14/src/lm/collision/query/lmCollideHull.cpp?at=default&fileviewer=file-view-default#lmCollideHull.cpp-113:127

I think Dirk's lecture talks about the same concept (maximizing area for final vertex via barycentric coordinates). To maximize area a triangle must already be present, say vertices A, B and C. The ordering of A to B to C is CCW. So if we maximize the area of D, then we just want to see if D is on the left or right side of a 2D plane to ensure ordering. I think I ensured this ordering on this line of code with a swap operation:

https://bitbucket.org/rgaul/lm/src/806fe4427db32f98e514c646b51f99ce1cfc5c14/src/lm/collision/query/lmCollideHull.cpp?at=default&fileviewer=file-view-default#lmCollideHull.cpp-102:104

Does that make sense? Maybe this is what you were looking for.

**Comment by irlanrobson** [comment]
Yes. I had already made the changes. Just need to fix some other stuff before commiting.

http://pastebin.com/BvJYJSwj

**Comment by irlanrobson** [comment]
For those who see the last two posts:

Our code doesn't ensure a contact quadrilateral with vertices ordered CCW. This is not a problem but is nice to have it ordered for debugging. 

The CCW order can be ensured by choosing any permutation of contact points that makes the quad CCW. These two predicates are usefull in this context (N is the contact normal):

`
static B3_FORCE_INLINE bool b3IsCCW(const b3Vec3& A, const b3Vec3& B, const b3Vec3& C, const b3Vec3& N)
{
	b3Vec3 n = b3Cross(B - A, C - A);
	return b3Dot(n, N) > 0.0f;
}

static B3_FORCE_INLINE bool b3IsCCW(const b3Vec3& A, const b3Vec3& B, const b3Vec3& C, const b3Vec3& D, const b3Vec3& N)
{
	return b3IsCCW(A, B, C, N) && b3IsCCW(C, D, A, N);
}
`
