### ISSUE TITLE
Bodies can't be constraint to Softbodies.

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#90]
When modelling a rope with soft bodies its not possible to constrain a body to it.

Bullet (for instance) allowed to constrain a body to a softbody node, and to offset the local space of the constraint. So it was possible to let physics bodies climb on ropes.

**Comment by irlanrobson** [comment]
I will see what I can do... Possibly allow to add a list of anchors to a soft body like Bullet does.

For your information, the other way around (that is, attaching a soft body node to a body) can be done by storing the node position in body coordinates and setting the node velocity to the linear velocity that will move the node from the current position to that position in world coordinates. For this to maintain physically correct simulation behaviour the node needs to be kinematic.

For examples check out the CapeTest in the testbed. It moves cloth particles in there. But you can carry on the same idea to soft body nodes.

**Comment by irlanrobson** [comment]
Don't play around with rigid body forces to solve this problem here since they are practically integrated explicity! (Semi-implicitly in theory)

**Comment by irlanrobson** [comment]
I added the anchor joints for you. The API is really simple:

b3SoftBody::CreateAnchor()
b3SoftBody::DestroyAnchor()

Use b3SoftBodyAnchorDef to define a anchor joint. There is an initialization function in there which takes an anchor in world coordinates and entities.

See the SoftBodyAnchor test in TestBed for examples.

**Comment by fredUmlaut** [comment]
Great, this adds a whole new dimension!
Thanks Irlan!

**Comment by irlanrobson** [comment]
I skipped over storing the second local anchor point relative to the node's origin. Now I am adding this for completeness.
