### ISSUE TITLE
How can I resize a cubic body without re - creating the shape?

### ISSUE THREAD

**Issue by mrjbom** [irlanrobson/bounce#91]
I have a pointer to the object b3Body, and a link to b3BoxHull, the body has the shape of a cube, how can I set new sizes?

**Comment by irlanrobson** [comment]
I don't handle these cases. I assume a constant resource is as its name suggests: constant!

**Comment by mrjbom** [comment]
I'll ask you another question.
How do I change the size b3BoxHull?

**Comment by irlanrobson** [comment]
Not sure what you are asking. Your question needs more ellaboration. Please be more specific!

**Comment by mrjbom** [comment]
I create a rigid body attached to it b3BoxHull, sometimes I need to change the size of the body. For example: first I created the body precipi to it, the case type b3BoxHull with dimensions of (1.0, 1.0, 1.0), then I needed to resize b3BoxHull for this body, how can I do this? That is, it was (1.0, 1.0, 1.0), and it was necessary to change the size of the shape to (2.0, 2.0, 2.0). How?

**Comment by irlanrobson** [comment]
First of all is not the body it is attached to a hull. The hull is attached to the body.

If you move the body, the shape follows it. They're related by a transform.

Naively you could just call b3BoxHull::Set(...) on the shared hull.

However, I don't recommend this. If you do this, there will be bugs. 

This means you should create a new shape and destroy the old shape.
