### ISSUE TITLE
Support for large worlds using doubles instead of floats for positions

### ISSUE THREAD

**Issue by Lagger625** [irlanrobson/bounce#92]
I'm planning to make a game with support for very large worlds, and needs to be highly performant. I was going to use Unity3D but discarded it because it uses floats everywhere. If a `RigidBody` gets 10k units away from the world origin, animation and physics become weird because of precision loss. World shifting isn't an option. I decided to use C++ because it is more performant than C#, and making my own engine allows me to choose the precision I need for anything.

So I chose Bounce to do physics, I think it makes the best fit for the game. The only problem I have is that the bodies need to use doubles for their positions, and no other "fitting" library supports easy switching to doubles. I tried to change the definition of `float32` from `float` to `double`, but many errors related to templates showed up. Changing `b3Vec3` to use doubles for position or even making my own `b3Vec3Double` are some ideas I have, but I'm asking here, what would be the **best** way to do this? By "best" I mean a way that doesn't break random things, easily configurable to switch from single to double precision, or doesn't cause innecessary performance drops (for example, using `double` for mass, acceleration or other things).

I think it would be a rather appealing improvement for the library if it supported large worlds, I can even do it myself, but I prefer to ask for advice to someone who knows the library better than me so I can save a lot of time.

**Comment by irlanrobson** [comment]
Research :)! 

Some people in the forums use floats for local coordinates and doubles for world coordinates. Makes sense, but I think this is inconsistent for a real-time engine. So it might be better to use doubles everywhere. Just a guess. I have no experience with this.

I am wrapping up a float/double with scalar type for you. This might be usefull for further detecting numerical errors.

**Comment by irlanrobson** [comment]
The requested changes have been made.

Woah, this ended up as a quite large refactor for doubles. 

I haven't used VS search and replace or regular expressions often as I needed to switch from float literals to scalar literals. So I practically revisited each project file and also changed some other things.

**Comment by irlanrobson** [comment]
Make sure you also change these constants to match whatever floating type you're using:

B3_MAX_SCALAR
B3_EPSILON

**Comment by Lagger625** [comment]
Thank you for your reply and refactoring. I will keep researching and testing to make my giant worlds a reality! I will be looking into pull requesting any improvement I make and find worth sharing.

**Comment by irlanrobson** [comment]
Sure. Good luck with your game!

**Comment by irlanrobson** [comment]
I would appreciate issues rather than pull requests first for discussion as declared in the readme file.
