### ISSUE TITLE
Feature request: Rotation for b3WeldJoint::SetAnchor()

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#93]
Currently b3WeldJoint::SetAnchor() can only set a position and calculates the
rotation from the bodies. 

I would like to set "weldJoint->m_referenceRotation" directly.

Perhaps like this
void b3WeldJoint::SetAnchor(const b3Vec3& anchor,b3Quat *q=0)
...
If quaternion q is !=0 then m_referenceRotation is overwritten with q, 
otherwise its calculated like currently implemented.

**Comment by irlanrobson** [comment]
Nah, I don't like checking pointers around. Works, but it is inconsistent in my opinion. I'll add a function to set the relative rotation for you.

**Comment by irlanrobson** [comment]
Use b3WeldJoint::SetReferenceRotation.

**Comment by fredUmlaut** [comment]
I missed that. Thanks!
