### ISSUE TITLE
Request: b3MeshTriangle without interleaved edges

### ISSUE THREAD

**Issue by fredUmlaut** [irlanrobson/bounce#94]
Previously in Bounce b3Triangle was used to hold indices to triangles. This was very handy because it usually was identical to triangles from visual meshes.
Now it has changed to 'b3MeshTriangle' which is interleaved with the edges, and so visual meshes must be duplicated for Bounce.

Would it be possible to have all edges at the end of b3MeshTriangle instead of interleaved? 
So it would be possible to still use the visual meshes without duplication.

**Comment by irlanrobson** [comment]
It still uses indices to triangles. The only thing has changed was that now it includes unique edges! It is the same mesh, but with some additional data.

The edges inside a mesh are not half-edges! A half-edge mesh cannot represent a non-manifold mesh. Otherwise I would have chosen it.

**Comment by irlanrobson** [comment]
The integers e1, e2, and e3 inside mesh are indices to the unique edges and not the indices to the half-edges.

**Comment by irlanrobson** [comment]
The vertices inside a unique mesh edge are not necessary but they are handy for debugging.

**Comment by irlanrobson** [comment]
I've added what you requested!

I scanned through your post really quickly. Sorry! You wanted to be able to simply cast the triangle index array in a renderable mesh to the triangle index array in the simulation mesh without having to clone the array.

**Comment by fredUmlaut** [comment]
Thanks Irlan!
