### ISSUE TITLE
Manual change of the degree of rotation disappears not exceeding 90 degrees

### ISSUE THREAD

**Issue by mrjbom** [irlanrobson/bounce#96]
Hello.
In my program, I change the degree of rotation of a solid body around an axis.

How I do it: I get the degree by which the figure is currently rotated along the axis and add the required degree to it.

Everything works fine, but as long as the _current degree + extra degree < 90 degrees_.
If the _current degree + extra degree is > 90 degrees_, then the next time you query the current degree, it returns the previous value (probably).

Here's the function code.
```
void editObject(int bodyNumber, b3Vec3 newPosition, b3Vec3 newSize, b3Vec3 axis, float extraAngleInDegress)
{
	b3Vec3 rotateInRadians = { };
	quaternion2Angle(body[bodyNumber]->GetOrientation(), rotateInRadians);
	b3Vec3 rotate = b3Vec3(
		RadiansToDegress(rotateInRadians.x),
		RadiansToDegress(rotateInRadians.y),
		RadiansToDegress(rotateInRadians.z)
	);
	
	//Define the axis to calculate the new rotation along the required axis
	//(1, 0, 0)
	if (axis.x == 1)
	{
		extraAngleInDegress += rotate.x;
	}
	//(0, 1, 0)
	else if (axis.y == 1)
	{
		cout << "----------\n" << "Current degree = " << rotate.y << "\nExtra degree = " << extraAngleInDegress << endl;
		cout << "Result degree = " << rotate.y << " + " << extraAngleInDegress << " = " << rotate.y + extraAngleInDegress << "\n\n";
		extraAngleInDegress += rotate.y;
	}
	//(0, 0, 1)
	else if (axis.z == 1)
	{
		extraAngleInDegress += rotate.z;
	}

	cout << "Result degree = " << extraAngleInDegress << "\nResult degree in radians = " << DegressToRadians(extraAngleInDegress) << "\n----------\n\n";
	body[bodyNumber]->SetTransform(newPosition, axis, DegressToRadians(extraAngleInDegress));
}
```

Here's the out:

![alt tag](https://i.ibb.co/B6wbvg0/08-11-2019-212421.png "Screenshot")​

In the last two outputs from the function you can see how instead of the expected 91 outputs again 90.

Up to 90 degrees everything was fine, but after-death.

P.S. The _quaternion2Angle()_ works correctly, there are no errors in it.

**Comment by mrjbom** [comment]
_SetTransform()_ setting one axis resets the others to 0, then how can I set multiple axes to the values I need?

For example, I want to set the following values for the three axes: X = 10°, Y = 30° ,Z = 5°, how do I do this? If I use _SetTransform()_ alternately, I won't be able to do it.

**Comment by irlanrobson** [comment]
Hi there.

In Bounce the order of quaternion multiplication is consistent with the order of matrix multiplication. That is, the composed rotation

qD = qA * qB * qC

rotates a vector by qC then by qB and finally by qA. 

With that in mind, you can easely compose rotations about any axis.

**Comment by mrjbom** [comment]
OK, but how can I set my quaternion? I'm trying to set my quaternion using b3BodyDef*->orientation = newQuaternion, but it does not affect the body;

How to use your orientation quaternion?

**Comment by mrjbom** [comment]
How can I set my quaternion? If I set it to _b3BodyDef_ then it has no effect.

**Comment by irlanrobson** [comment]
> If I set it to b3BodyDef then it has no effect.

This is completely wrong! I use this in a lot of tests for setting the initial orientation of a body and I never had a problem. The same is true for SetTransform. Maybe you are not sure what the expected results are.

Maybe you should read this:

https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles

You certainly can find tons of resources about this out there.

**Comment by mrjbom** [comment]
I want to be able to set 3 rotations around three axes at once. I can't use SetTransform for this task because It only sets the rotation along one axis(or several but by the same degree) and resets the rest to 0.

I know how to convert Euler angles into a quaternion, but I can't apply it to a body.

How do I rotate the body along multiple axes?

**Comment by mrjbom** [comment]
I know how to convert Euler angles into a quaternion, but I can't apply it to a body. 

I want to be able to set 3 rotations around three axes at once. I can't use SetTransform for this task because It only sets the rotation along one axis(or several but by the same degree) and resets the rest to 0. 

How do I rotate the body along multiple axes?

**Comment by irlanrobson** [comment]
> I can't use SetTransform for this task because It only sets the rotation along one axis(or several but by the same degree) and resets the rest to 0.

In 3D any rotation can be defined by an axis and an angle of rotation about that axis. A quaternion represents a rotation encoding the axis and angle of rotation. 

It seems that you want to find a final rotation from consecutive rotations. I am not sure what you mean by resets the other angles to zero. As you're asking those kinds of questions it looks like you have superficial understanding of rotation quaternions. Perhaps that's a good time to learn more about them! This presentation by Jim is a good introduction to quaternions:

https://www.essentialmath.com/GDC2013/GDC13_quaternions_final.pdf

Don't worry about digging the habbit hole deeply. Bounce doesn't require the user is a quaternion expert. 

> How do I rotate the body along multiple axes?

One way to achieve this is to compose rotations around axes. For example, this code would rotate the body around the standard world axes:

```
b3Quat qX = b3QuatRotationX(aX);
b3Quat qY = b3QuatRotationY(aY);
b3Quat qZ = b3QuatRotationZ(aZ);

b3Quat qR = qZ * qY * qX;

// Composing many rotations may lead to round-off errors. Therefore, we normalize the quaternion.
qR.Normalize();

// Set the initial rotation quaternion.
b3BodyDef def;
def.orientation = qR;
...
```

**Comment by mrjbom** [comment]
Okay, you showed me how to specify my quaternion to initialize a body, but how can I apply it to a body that already exists? 

After all, changing b3BodyDef which was used when creating this body does not change anything.

How to do all this for an already existing body?

**Comment by irlanrobson** [comment]
You should use SetTransform. I use this in my tests. It has never failed. If something goes wrong, you're probably misusing it.

**Comment by mrjbom** [comment]
A bit silly question.
But could you tell or point out what principle SetTransform works, I do not fully understand what axis to transfer there.

I can rotate around what the one axis, but what vector axis cede to rotate on several different angles and what degree of reverberates in this case peredovat.

**Comment by mrjbom** [comment]
SetTransform() sets the rotation of the body using spherical coordinates?

What is meant by "axis" in params?

How can I calculate this axis for the required rotations along the three axes?

**Comment by irlanrobson** [comment]
The last version of the library allows the user to set the position and orientation of the body via SetTransform. This function takes a point and a quaternion as parameters. This function is implemented here:

https://github.com/irlanrobson/bounce/blob/master/include/bounce/dynamics/body.h#L511

There is no axis as parameter anymore. You are probably running an older version if you see an axis there.

**Comment by mrjbom** [comment]
Oh, great. Yes, my version is older than the one we talked about.

We just talked about different versions of the function and could not understand each other :)

Thanks for your help!

**Comment by irlanrobson** [comment]
In an older version you would extract the axis and angle of your desired rotation and pass those to the SetTransform function. Example:

```
// Build the desired rotation
b3Quat qR = ...

// Extract axis and angle
b3Vec3 axis;
scalar angle;
qR.GetAxisAngle(&axis, &angle);

// Set orientation from axis and angle. 
// Internally this would set the quaternion from axis and angle.
body->SetTransform(position, axis, angle);

// Now the body orientation is set to qR.

```
Glad I helped!
