### ISSUE TITLE
The quaternion returns the wrong angle

### ISSUE THREAD

**Issue by mrjbom** [irlanrobson/bounce#97]
Hello.

I ask the angles of inclination of the body using the methods of the quaternion.

I do it with this construct and then rotate the body using OpenGL.

```
	glPushMatrix();
	glRotatef(RadiansToDegress(body[bodyNumber]->GetOrientation().GetXAngle()), 1, 0, 0);
	glRotatef(RadiansToDegress(body[bodyNumber]->GetOrientation().GetYAngle()), 0, 1, 0);
	glRotatef(RadiansToDegress(body[bodyNumber]->GetOrientation().GetZAngle()), 0, 0, 1);

	glBegin(...);
        ...
        glEnd();
        glPopMatrix();
```

The position is rendered itself partially correctly. But it is not behaving correctly.
For example:
![alt tag](https://i.ibb.co/hFWfJ2S/11-11-2019-195517.png "11-11-2019-195517")​

**Comment by irlanrobson** [comment]
I think you have a small problem with the order of rotations. Recall each call to glRotatef multiplies the current matrix by the rotation matrix built from axis and angle.

For avoiding problems when using Euler angles you can build a 4x4 rotation matrix from the quaternion and use glMultMatrixf. This is much more error prone and what people do nowadays.

Example:

```
// Grab orientation
b3Quat qR = body->GetOrientation();

// Convert the quaternion to a rotation matrix
b3Mat33 R = qR.GetXYZAxes();

// Build each column of the corresponding 4x4 rotation matrix
b3Mat44 T;
T.x = b3Vec4(R.x.x, R.x.y, R.x.z, 0);
T.y = b3Vec4(R.y.x, R.y.y, R.y.z, 0);
T.z = b3Vec4(R.z.x, R.z.y, R.z.z, 0);
T.w = b3Vec4(0, 0, 0, 1);

glPushMatrix();

// T is stored in colum-major so it is okay to pass a pointer to the first value because 
// OpenGL also uses column-major storage.
glMultMatrixf(&T.x.x);

...

glPopMatrix();
```

**Comment by irlanrobson** [comment]
It has been a long time since I used the fixed-function pipeline of OpenGL so in addition you might consider verifying the order of OpenGL calls are correct.

**Comment by mrjbom** [comment]
Now everything works correctly.

In the past, when I was working with the old version of the library, I would convert the quaternion to Euler angles and perform turns. Everything worked well. I don't understand why this doesn't work with the new version where I get the angles directly by quaternion methods.

Thank you, thank you for your help!
